### PR TITLE
User home screen + tidy ups

### PR DESCRIPTION
**Pull request by aptkingston**
### User home screen
This adds the "normal" (non-builder) user home screen, which is a list of apps they can access as well as a few utilities to edit their account. I've had to cut a couple of things from Joe's designs for this screen because we don't have the functionality yet - things like groups.

Designs: https://xd.adobe.com/view/39323f7c-ada5-474b-85b3-6d2f83db8a0c-6c61/screen/075f2258-6e09-423c-a5bd-f2c9d9fbbae5

image

Users can update their first name and last name and change their password using the dropdown from the avatar. They can also go to developer mode (the portal) if they're a builder user.

image
image
image

### Global user changes
 First name and last name have been added to the global user doc as part of this change. These are editable from the dropdown, and are also listed in the portal screen when a user is selected.

Editing global user fields from inside the builder (i.e. when inside an app) has been removed. You can't create or delete users, and all global fields are disabled when editing users. This means you can only create / edit / delete user metadata pertaining to the specific app, but can't change anything that affects the global user docs.

### Other stuff
- I've updated the general settings so that you can see the current company logo, and also preview the company logo you're about to upload.
image
- I've also gone through all the portal screens and updated the spacing in the layouts to be identical to each other, so it feels nice and consistent. 
- Fixed various wee bugs here and there that I came across while testing
- You can also "Close" developer mode (the opposite of opening it from the user home screen) to back to the default user home screen, from the avatar dropdown again

Thanks to @mike12345567 for jumping in and doing some of the global user changes in parallel to speed things up!

### CODE REVIEW

**Comment by joebudi** [comment]
Incredible work here. Well done.

Do you think we should charge 'edited' to 'updated' in the app list

**Comment by aptkingston** [comment]
> Incredible work here. Well done.
> 
> Do you think we should charge 'edited' to 'updated' in the app list

Can do. We don't actually have those timestamps yet actually, so we need to implement it properly. But yea the text sounds better as updated.

**Review by kevmodrome — APPROVED** [review]
LGTM!

**Review by shogunpurple — APPROVED** [review]
Amazing stuff @aptkingston and @mike12345567 - This really brings the portal together! 🚀

**Pull request merged**
