### PR TITLE
Apply affinities and tolerations in the helm chart

### LINKED ISSUE #5423: Affinities and tolerations not applied in helm chart
**Describe the bug**

Although the values.yaml declares `tolerations: []` and `affinity: {}` they are not actually applied in any of the `*-service-deployment.yaml` files.

**To Reproduce**

1. Add an affinity or toleration in the value.yaml
2. Run `helm install budibase .`
3. Confirm that none of the pods deployed have an affinity or tolertion

**Expected behavior**

When declaring a toleration or affinity in the values.yaml it's propagated to the underlying k8s resources.

### PR DESCRIPTION
**Pull request by dougwettlaufer**
## Description

The affinities and tolerations in the values.yaml were not added to the `*-service-deployment.yaml` files. Resolves #5423

### CODE REVIEW

**Comment by dougwettlaufer** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by dougwettlaufer** [comment]
recheck

**Comment by dougwettlaufer** [comment]
recheck

**Review by shogunpurple — APPROVED** [review]
Thanks for the contribution @dougwettlaufer!

**Pull request merged**
