### PR TITLE
Spectrum themed apps

### LINKED ISSUE #1822: I cannot change the button variant within my auto-generated table
**Describe the bug**
I cannot change the button variant within my auto-generated table. When I select cta/secondary, nothing happens

**To Reproduce**
1. Auto-gen list screen
2. Click on the button
3. Try to change the variant

### PR DESCRIPTION
**Pull request by aptkingston**
## Description
This PR updates all components to work with spectrum theming, replaces cards with a new spectrum card component and enables spectrum theming of client apps.

themes

### Component update
All components have been updated to only use spetrum variables for colours. All hard-coded colours have been replaces with their equivalent spectrum variables, meaning all components will update to reflect the app theme.

### Cards
The existing verical card, horizontal card and stacked list components have been removed, and a new spectrum-based card component has been added.

image
image

Cards have settings for title, subtitle, description, image URL, link URL and a boolean for horizontal layout. The only required setting is the title - all other settings are optional. If a link URL is provided, the card title will be a link to the specified URL, which can be external or internal. 

Cards can be made horizontal using the provided checkbox. The largest impact of this is the position of the image, but it also provides a larger base width.

image

### Spectrum theming of apps
Client apps can now be themed using a dropdown to the top-right of the preview. This is fully independent of the builder theme. The client theme also determines the appearance of the in-preview settings bar, and affects the color palette available in the builder.

image

This lays the foundation for an actual theme update in future, where users can create a custom palette of colours to style their apps. This is now easily possible by overriding some spectrum variables.

### Autoscreen updates
In order to support the new spectrum-themed apps, autoscreens have had to change slightly to a more "floaty" design - basically just removing the coloured content background.

A nice consequence of the autoscreen updates is that pretty much all the custom styles have been removed! This means that all the styles in the autoscreen are visible in the component settings and can be easily copied or changed, whereas before we had hardcoded custom styles in which were not changeable or immediately obvious (looking at you - delete button).

image
image

### Misc changes and fixes
- Added back in hot reloading to the server. This was lost in the typescript update due to nodemon being removed. I've combined them both, so nodemon now watches for file changes and restarts ts-node as required.
- Replaces the button in auto-generated tables with a link. Closes #1822.
- The builder preview will always be logged in as the current user rather than the "first" user. There is an issue or discussion around this but I can't find it for the life of me. But this fixes that issue.
- Fix a bug where a 409 conflict causes a layout named `undefined` to appear
- Fix a bug where the custom CSS drawer showed stale data when changing components
- Fix a loophole where the API call to fetch the app package could be called by any user, but actually included the full definitions of all screens and layouts even if that user should not be able to see them
- Add custom scrollbars (same as builder) to client apps

### CODE REVIEW

**Comment by joebudi** [comment]
Awesome works Cheeks. This is beautiful and a real UI achievement for Budibase. I believe this will make a lot of end-users happy and potentially improve end-user time-in-app.

**Review by shogunpurple — APPROVED** [review]
Awesome job. Some nice wee extra fixes in there as well! 🚀

**Comment by mike12345567** [comment]
Love this, such a big improvement, love the PR too, looks like a release in and of itself! 🎊

**Comment by Rory-Powell** [comment]
So so good, appreciate the detailed description as well

**Pull request merged**
