### PR TITLE
Fix for exported data UI display issues

### PR DESCRIPTION
**Pull request by deanhannigan**
## Description

Minor refactor to fix export modal table. `onEmptyFilter` is filtered out to ensure config items build only valid rows.

### Addresses:
- https://linear.app/budibase/issue/BUDI-7601/wrong-filters-while-exporting-data

## Feature branch env
[Feature Branch Link](http://fb-fix-export-data-ui.fb.qa.budibase.net)

### CODE REVIEW

**Review by shogunpurple — CHANGES_REQUESTED** [review]
It would be good to have a test for this, if possible

**Review by aptkingston — APPROVED** [review]
LGTM!

**Comment by aptkingston** [comment]
@shogunpurple could you approve so we can merge this one? Thanks.

**Review by shogunpurple — APPROVED** [review]
LGTM!

**Pull request merged**
