### PR TITLE
Verbose actions

### PR DESCRIPTION
**Pull request by adrinr**
## Description
Fixing payloads to send the expected fields.
1. The `PAYLOAD_VERSION`will be used for checking out the monorepo on the release process.
2. The `REF_NAME` will be used as display name following https://github.com/Budibase/budibase-deploys/pull/147

### CODE REVIEW

**Review by shogunpurple — COMMENTED** [review]
Why is this required?

**Comment by adrinr** [comment]
> Why is this required?

This is used as inputs for the QA release pipeline: https://github.com/Budibase/budibase-deploys/pull/147
Added more details on the PR description

**Review by shogunpurple — APPROVED** [review]
LGTM!

**Review by mike12345567 — APPROVED** [review]
LGTM!

**Pull request merged**
