### PR TITLE
Chore: Allow using an AWS_SESSION_TOKEN for object storage with AWS S3

### LINKED ISSUE #13884: Support for aws session token when using temporal AWS credentials for S3 object storage
**Scenario:**

- Using AWS S3 as object storage instead of Minio
- AWS credentials are automatically rotated or are session based, therefore the AWS Credentials will require an extra config parameter called `sessionToken` or defined by the env var `AWS_SESSION_TOKEN`
- The AWS session token is for regular configuration an optional parameter, only when provided should be taken into the client config

### PR DESCRIPTION
**Pull request by refucktor**
## Description

The current configuration for the AWS S3 client library doesn't support the existence of an AWS_SESSION_TOKEN, hence the operations with the object store are showing Unauthorized errors

## Addresses
- Close #13884

### CODE REVIEW

**Review by samwho — APPROVED** [review]

**Comment by samwho** [comment]
Thanks for another contribution, @refucktor! 🙏

**Comment by samwho** [comment]
@refucktor would you be able to pull the latest `master` into your branch and push it up? You've picked up a build problem by accident that we fixed recently. 🙏

**Comment by refucktor** [comment]
@samwho, I just updated with the latest from master, let me know if that's sufficient 😃

**Comment by mike12345567** [comment]
Hi @refucktor - thanks for the submission - merging to a branch to investigate CI failure.

**Pull request merged**
