### PR TITLE
turn off websockets in client lib in cloud

### PR DESCRIPTION
**Pull request by shogunpurple**
## Description
Turn off initialisation of websocket client in cloud as it does not add anything and is causing issues:

Addresses: 
- https://github.com/Budibase/budibase/issues/7903#issuecomment-1255053348

## Screenshots
_If a UI facing feature, a short video of the happy path, and some screenshots of the new functionality._

### CODE REVIEW

**Review by Rory-Powell — APPROVED** [review]

**Review by aptkingston — APPROVED** [review]
Probably still worth investigating why the websocket wasn't connecting in cloud (because it should) but I agree it adds nothing in cloud so makes sense to disable it.

**Comment by Rory-Powell** [comment]
I wonder is this related to multi instances behind the load balancer. Maybe the connection is being opened initially to one instance, with subsequent communication is being routed through the generic address of bb.budibase.app finding the connection no longer is alive

**Comment by aptkingston** [comment]
> I wonder is this related to multi instances behind the load balancer. Maybe the connection is being opened initially to one instance, with subsequent communication is being routed through the generic address of bb.budibase.app finding the connection no longer is alive

Yea could definitely be that. I assume we haven't needed to enable any sort of session stickiness until now.

**Comment by aptkingston** [comment]
> @aptkingston it's weird because as I showed you it semi-works for me, I never fully lose connection to the websocket, just some requests.
> 
> Screenshot_2022-09-22_at_14 57 17

That maybe supports the idea though that the requests which make it through to the original node work, and the rest don't? Although strange that it fails 100% of the time for me.

**Comment by shogunpurple** [comment]
> 
I wonder is this related to multi instances behind the load balancer. Maybe the connection is being opened initially to one instance, with subsequent communication is being routed through the generic address of bb.budibase.app finding the connection no longer is alive

This is a good shout - I think we need to repro this in a clustered env in one of our test environments and see if we can get websockets working across pods

**Comment by Rory-Powell** [comment]
good advice on multi nodes / stick sessions
https://socket.io/docs/v4/using-multiple-nodes

there's steps in here for nginx, not sure about how that will also work with amazons ELB. I assume there is similar configuration

**Pull request merged**
