### PR TITLE
BUDI-6685 - SCIM usergroup lockdown

### PR DESCRIPTION
**Pull request by adrinr**
## Description
Blocking user and group edition when SCIM feature is enabled. UI changes described here: https://www.figma.com/file/jA3KI85k4eFqfoQMMtLkly/SCIM?node-id=1-111&t=c9nm6utdA3fRJ1h6-0

Addresses: 
- https://linear.app/budibase/issue/BUDI-6685/scim-usergroup-lockdown

## App Export
Not required

### Users list
image

### Users detail
image

### Groups list
image

### Group detail
image

### CODE REVIEW

**Comment by PClmnt** [comment]
image I wonder if for SCIM should we update GroupNameTableRenderer to not show an icon? Because that gap where an icon would normally be looks a bit strange. So for SCIM it would just be the name.

**Comment by adrinr** [comment]
> > I wonder if for SCIM should we update GroupNameTableRenderer to not show an icon? Because that gap where an icon would normally be looks a bit strange. So for SCIM it would just be the name.
> 
> Would be nice if we could get it to create the group with an icon, just the default one we see when creating a new group would be good

This is set on the creation process, in the backend. I had it as a TODO. Let me update the screenshots

**Comment by adrinr** [comment]
> > > I wonder if for SCIM should we update GroupNameTableRenderer to not show an icon? Because that gap where an icon would normally be looks a bit strange. So for SCIM it would just be the name.
> > 
> > 
> > Would be nice if we could get it to create the group with an icon, just the default one we see when creating a new group would be good
> 
> This is set on the creation process, in the backend. I had it as a TODO. Let me update the screenshots

PR adding the icon as expected: https://github.com/Budibase/budibase-pro/pull/145
@Rory-Powell @PClmnt

**Comment by PClmnt** [comment]
> > > > I wonder if for SCIM should we update GroupNameTableRenderer to not show an icon? Because that gap where an icon would normally be looks a bit strange. So for SCIM it would just be the name.
> > > 
> > > 
> > > Would be nice if we could get it to create the group with an icon, just the default one we see when creating a new group would be good
> > 
> > 
> > This is set on the creation process, in the backend. I had it as a TODO. Let me update the screenshots
> 
> PR adding the icon as expected: [Budibase/budibase-pro#145](https://github.com/Budibase/budibase-pro/pull/145) @Rory-Powell @PClmnt

Awesome @adrinr! LGTM

**Review by PClmnt — APPROVED** [review]

**Pull request merged**
