### PR TITLE
WIP: add Azure App Service image to docker registry

### PR DESCRIPTION
**Pull request by jonnymccullagh**
## Description
Make it easier to pull an image for Azure App Service by building/tagging a specific image in the docker registry

### CODE REVIEW

**Review by shogunpurple — APPROVED** [review]
LGTM!

**Review by mike12345567 — APPROVED** [review]
LGTM! Might just want to change this to merge to `master` rather than `develop` so that it can be released asap.

**Comment by mike12345567** [comment]
Closing as needed to rebase to master.

**Review by mike12345567 — COMMENTED** [review]
-

**Pull request closed without merging**
