### PR TITLE
Feature/map component

### PR DESCRIPTION
**Pull request by deanhannigan**
## Description

Addresses https://github.com/Budibase/budibase/issues/3819

- New 'EmbeddedMap' component. Found under 'Elements' in the builder.
    - Zoom, Location and Fullscreen controls can added/removed as required.
- Geolocation Control
    - Will attempt to determine the users location and refocus the map upon success.
    - Dependent on the current devices location permissions being enabled.
- Fullscreen Control
    - 'screenfull' has been added to the client package to facilitate fullscreen behaviour
- Configurable tile URL
    - OpenStreetMaps **(Default)** - https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png
    - Google - http://mt1.google.com/vt/lyrs=y&x={x}&y={y}&z={z}
    - Be mindful of API licensing when specifying a custom Tile URL.
- Markers
    - Wrap the EmbeddedMap with a DataProvider and provide field configuration for:
        - Latitude Key **(Required)**
        - Longitude Key **(Required)**
        - Title Key **(Optional)**
    - Any valid markers will be displayed on the map. 
    - On load, the map will attempt to fit all markers into view.

## Screenshots
builder_map

client_map

### CODE REVIEW

**Comment by joebudi** [comment]
@deanhannigan this is awesome! I really like the enable location option.

**Review by shogunpurple — CHANGES_REQUESTED** [review]
This is a really nice piece of work 👍 Just a few things - looking back at the spec, we have button actions for both a marker click and for marker creation. I don't think these have been accounted for here.

Some other things:
- Missing "enable add marker" option
- Missing default location option

Going to pull this down and have a play around with the interactions too. 👍

**Comment by aptkingston** [comment]
> This is a really nice piece of work +1 Just a few things - looking back at the spec, we have button actions for both a marker click and for marker creation. I don't think these have been accounted for here.
> 
> Some other things:
> 
>     * Missing "enable add marker" option
> 
>     * Missing default location option
> 
> 
> Going to pull this down and have a play around with the interactions too. +1

I can explain those! I've had a couple of calls with Dean about this stuff. For the default location - I felt that a default location setting made no sense, because why would you want a default location when you have markers, since you'd just want to zoom to those. However you do need a default location when no markers exist, so we should indeed add it. That's my bad, and Dean is on this now :+1: 

As for the actions (on marker add, on marker click), I thought it was best to tackle those myself because it's a new core concept for the client library. I'll be running Dean through my ideas and how it works though. The map as it is in this PR is a fully functional map for displaying data that can be added via forms, or just displaying data stored in any data source. I don't mind if you'd prefer to keep this open until the actions have been added, or we can merge this and add the actions as a separate PR.

**Comment by deanhannigan** [comment]
@shogunpurple I have the updated default location elements locally and will push them today with some other updates.

**Review by aptkingston — COMMENTED** [review]
This is amazing for a first PR @deanhannigan! Pulled this down and had a play and everything worked as expected. Can't find any faults in the code, but one thing I think we should do is move this inside its own folder since there are 2 files, and we generally put anything more than a single file into a folder.

Just literally `components/app/embedded-map/EmbeddedMap.svelte` and fire the controls file in beside it.

Super work :rocket:

**Comment by shogunpurple** [comment]
Awesome @aptkingston, thanks for the detail 👍 

> As for the actions (on marker add, on marker click), I thought it was best to tackle those myself because it's a new core concept for the client library. I'll be running Dean through my ideas and how it works though. The map as it is in this PR is a fully functional map for displaying data that can be added via forms, or just displaying data stored in any data source. I don't mind if you'd prefer to keep this open until the actions have been added, or we can merge this and add the actions as a separate PR.

All good, that makes total sense to split things up like that in that case.

Also concur that this is serious going for a first PR - you've considered a ton of edge cases when using maps and it's working really well - had a play around with it. Nice work @deanhannigan 👌

**Comment by daawaan** [comment]
hello, is there an estimated time of release for this one already?

**Comment by shogunpurple** [comment]
@daawaan this will be going out over the next couple of weeks. Thanks

**Review by shogunpurple — APPROVED** [review]
LGTM!

**Review by aptkingston — APPROVED** [review]
Get 'er merged!

**Comment by Samirmabrouk** [comment]
Tack


________________________________
Från: Andrew Kingston ***@***.***>
Skickat: den 25 mars 2022 12:56
Till: Budibase/budibase ***@***.***>
Kopia: Samirmabrouk ***@***.***>; Manual ***@***.***>
Ämne: Re: [Budibase/budibase] Feature/map component (PR #4856)


@aptkingston approved this pull request.

Get 'er merged!

**Pull request merged**
