### PR TITLE
Responsive portal

### PR DESCRIPTION
**Pull request by aptkingston**
## Description
This PR updates the portal to be responsive, improves the consistency of the layout of all the portal pages and adds support for some unique mobile features.

The most obvious functional change is the drawer menu which can be opened using the new burger menu that will appear on mobile.

image

There were a bunch of changes to how certain components were laid out to better work on smaller resolutions, and a lot of style inconsistencies, bugs and strange choices have been fixed. The whole portal should look a bit better in general, and should now be fully mobile compatible too.

The rest of the changes are best explained by screenshots.

#### App card view
image

#### App table view
image

#### Users home
image

#### User details
image

### Auth
image

#### Email settings
image

#### Email template
image

### Organisation
image

### Theme
image

### Updates
image

### User apps
image

### CODE REVIEW

**Review by shogunpurple — APPROVED** [review]
LGTM! This looks slick now on mobile 👌

**Comment by Rory-Powell** [comment]
wow!!

**Comment by joebudi** [comment]
Beautiful!

**Comment by mike12345567** [comment]
Amazing!!!

**Pull request merged**
