### PR TITLE
Home page UI design

### PR DESCRIPTION
**Pull request by joebudi**
Screenshot 2020-05-25 at 16 47 05

The majority of HTML and CSS is complete.

Still to be done by someone must better than me:
- Activate the 'create new web app' button
- Activate the settings nav item
- Activate date modified
- Ability to rename web app and provide a description (and an auto screenshot is generated down the line)

### CODE REVIEW

**Review by shogunpurple — COMMENTED** [review]
LGTM apart from one thing - move your images from `server/builder/assets` to `builder/assets`. This means they won't get blown away when we do a fresh build

**Comment by joebudi** [comment]
Strange. I didn't put them there. The images I used are in builder/assets.

**Comment by shogunpurple** [comment]
Oh, that's fine then. The build has just added them to `server/builder`. Think we need to just ignore that folder in git 👍

**Comment by joebudi** [comment]
Should I merge?

**Comment by shogunpurple** [comment]
@joebudi sorry only seeing this. You will have to fix the lint errors before merging.

`yarn format`
`yarn lint`

**Comment by joebudi** [comment]
Awesome. Cheers

**Comment by kevmodrome** [comment]
I'll get working on the create app functionality

**Pull request merged**
