### PR TITLE
Re-add code that was removed to fix App Action fields null-pointer

### PR DESCRIPTION
**Pull request by melohagan**
## Description
Recent code change removed a cloneDeep, but it's needed!

Addresses: 
- https://github.com/Budibase/budibase/issues/10051

### CODE REVIEW

**Review by PClmnt — APPROVED** [review]

**Comment by aptkingston** [comment]
Is it actually the clone that's needed, or just always an assignment to block inputs? As we've discussed before, we shouldn't have these clones all over the place - the goal is to remove them. If the clone is actually needed then it means there's other mutation going on that we need to fix.

**Comment by aptkingston** [comment]
I'll have a look at the original issue and root cause it.

**Comment by melohagan** [comment]
Thanks @aptkingston !

I was going to go ahead and deploy this fix anyway just because it is a fairly bad breaking change.

**Comment by aptkingston** [comment]
Yep makes sense, no problem!

**Pull request merged**
