### PR TITLE
Adds BASH_SCRIPTING_TIMEOUT environment variable

### PR DESCRIPTION
**Pull request by upgreydd**
## Description
Adds `BASH_SCRIPTING_TIMEOUT` environment variable for Bash Scripting step in Automation

### CODE REVIEW

**Comment by Upgreydd** [comment]
recheck

**Review by shogunpurple — CHANGES_REQUESTED** [review]
Hi @Upgreydd - we cannot allow this to be configurable at the automation level, as it could allow people to set it to very large timeouts and block operations in our cloud. I will add an environment variable that you will only be able to set in self host to control this property.

**Comment by Upgreydd** [comment]
@shogunpurple OK, I've updated it

**Comment by Upgreydd** [comment]
> I have read the CLA Document and I hereby sign the CLA

**Comment by Upgreydd** [comment]
retrigger

**Comment by Upgreydd** [comment]
recheck

**Review by shogunpurple — APPROVED** [review]
LGTM! Thanks for the contribution.

**Comment by Upgreydd** [comment]
@shogunpurple Thanks man, I've pushed one more fix - question is when it can be released? :D

**Comment by shogunpurple** [comment]
Hi @Upgreydd - apologies, but we think we have found a better approach to this. Just using the total automation timeout inside the bash step prevents us introducing a new environment variable. 

https://github.com/Budibase/budibase/pull/5267

If you would like to update your PR to reflect, I can merge it - or we can close this one and just merge mine. I'll get it released today either way 👍

**Comment by Upgreydd** [comment]
> Hi @Upgreydd - apologies, but we think we have found a better approach to this. Just using the timeout that we use for our queries inside the bash step prevents us introducing a new environment variable.
> 
> #5267
> 
> If you would like to update your PR to reflect, I can merge it - or we can close this one and just merge mine. I'll get it released today either way +1
Thanks,
Lets merge your mate :+1: 
I'll close mine

**Pull request closed without merging**
