### PR TITLE
Added lerna to the prerequisites for contributors

### PR DESCRIPTION
**Pull request by johnnycardy**

### CODE REVIEW

**Comment by shogunpurple** [comment]
Thanks for your PR! However to use budibase, users don't need to install lerna globally. By running a `yarn install` followed by `yarn <lerna-command>` you can make use of the local version of lerna, rather than global. We could possibly update the docs to make this more clear.

**Comment by mjashanks** [comment]
Thanks @johnnycardy  ! Good to hear from you!  xox

**Review by mjashanks — APPROVED** [review]
@johnnycardy  welcome as our first external contributor!... I'm undoing your change after i've approved this btw.

**Comment by johnnycardy** [comment]
> welcome as our first external contributor!... I'm undoing your change

That is both hilarious and confusing in equal parts! Why not just reject it?

Anyway, the issue I was trying to address is that the contributor guidelines don't work as-is. Specifically the `yarn bootstrap` command (which the package.json defines as `lerna bootstrap`) gives this error...

```
yarn bootstrap
yarn run v1.21.1
$ lerna bootstrap
'lerna' is not recognized as an internal or external command
```

**Comment by mjashanks** [comment]
> Why not just reject it?
we now have another contributor! 

I also refer you to our [contributor guidelines, ](https://rfc.zeromq.org/spec:42/C4/) section 2.4, No. 16... I'll categorise this as "(c) engaging with the Contributor on improving their patch quality." !

I've reported this as an issue: https://github.com/Budibase/budibase/issues/71

Cheery Johnny.

**Pull request merged**
