### PR TITLE
Bumps Routify and Svelte to 3.35

### PR DESCRIPTION
**Pull request by kevmodrome**
## Description
This PR bumps routify to V2 and Svelte to 3.35.

## Screenshots
No visual changes

### CODE REVIEW

**Comment by kevmodrome** [comment]
This seems to error when there's a datasource of some kind connected to any component in in the routes in the design section. Waiting until #1278 is done to see if that helps.

**Comment by shogunpurple** [comment]
@kevmodrome What is the exact error you are seeing?

**Comment by kevmodrome** [comment]
I don't remember the exact wording of the error but it's the `something something 'target' is missing from ...` that shows up sometimes when navigating in the design section

**Comment by shogunpurple** [comment]
Should we try pulling https://github.com/Budibase/budibase/issues/1278 and see if this resolves the issues?

**Comment by kevmodrome** [comment]
Sorry Martin, missed this one. This branch has been merged in to the branch that Andrew has been working on these last few days. The plan there is to get it merged in today or tomorrow so it makes more sense to just get this PR in via that branch rather than get this one sorted

**Pull request closed without merging**
