### PR TITLE
Add Goto If Action

### PR DESCRIPTION
**Pull request by IchthysMaranatha**
Hi, have also added changes for restricting loops according to this post
https://github.com/Budibase/budibase/discussions/10123#discussioncomment-5448456
Have not built and tested after that

Address:
 - https://github.com/Budibase/budibase/issues/7016

Simple *Finally* use-case:
Screenshot 2023-03-31 at 08 45 46

goto

### CODE REVIEW

**Comment by IchthysMaranatha** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by melohagan — CHANGES_REQUESTED** [review]
Add a Goto If / Else (see comment above).

**Comment by IchthysMaranatha** [comment]
It's a jump only if condition is met, if not it will go to the next action by default. No need of else here. You have to configure steps accordingly to get the if then else construct. https://github.com/Budibase/budibase/discussions/10123#discussion-5009639

**Comment by IchthysMaranatha** [comment]
Because if both are jumps what would be the point of the action just after the go to if action?

**Comment by IchthysMaranatha** [comment]
In your case you've jumped to next step with goto if, which it will go to anyway even if condition is not met. For Goto if, go to step must always be something that is not in the normal progression, just like in any programming language that supports goto.

**Comment by melohagan** [comment]
> Because if both are jumps what would be the point of the action just after the go to if action?
> In your case you've jumped to next step with goto if, which it will go to anyway even if condition is not met. For Goto if, go to step must always be something that is not in the normal progression, just like in any programming language that supports goto.

That makes sense! It probably is grand then, but I would like the product team to have a look over this as well just to be sure they're happy with the flow.

**Comment by melohagan** [comment]
Hey @IchthysMaranatha 

I had a chat with the team and our product manager, and we have decided for now that this feature isn't quite what we want for the core product, but there is no time frame for when we would implement this. Possibly we could allow flexible scripts for users who need advanced action flows, but that's just an idea! 

With that said I really appreciate the contribution effort! To help us in future, what specific use-case were you trying to solve using 'Go To' actions?

**Pull request closed without merging**
