### PR TITLE
FIX: queries use blank string instead of column default value

### PR DESCRIPTION
**Pull request by melohagan**
## Description
Blank query bindings were passing empty strings into the SQL queries, which was causing errors for number types.

Fixed so that blank bindings for SQL queries now use null instead, which is also consistent with the row mapper: https://github.com/Budibase/budibase/blob/master/packages/server/src/utilities/rowProcessor/map.ts
 

## Addresses
- https://github.com/Budibase/budibase/issues/11629

### CODE REVIEW

**Review by samwho — COMMENTED** [review]
This is making my spidey-senses tingle.

What if we're legitimately trying to save an empty string to a column?

What's preventing whatever's upstream of this code from correctly sending null?

**Comment by melohagan** [comment]
@samwho This is a visual of the problem here:

Screenshot 2023-11-29 at 10 30 48

Because the bindings use a text field, leaving the default value blank will pass an empty string.

It's impossible to pass `null`, as it gets converted to a string:

Screenshot 2023-11-29 at 10 31 51

Even in the case of trying to pass `null` via JS in the Design section, it will interoperate `null` as ignore, which will then try to use the invalid default value. 
 
Screenshot 2023-11-29 at 10 34 24

**Comment by samwho** [comment]
That's a pickle.

I'm going to wait to see what Mike says, but with my relatively new-to-the-codebase eyes it feels like coercing `""` to `null` at the query building layer isn't the right solution. It has too much scope to mess with other things.

If it's possible to find a layer higher up to do this coercion, that specifically addresses this problem with bindings, that would be preferable I think.

**Comment by mike12345567** [comment]
Yeap agree with @samwho - I think doing this at the actual datasource implementation level means things will be missed, for example the Oracle datasource is not covered by this.

I believe if we could move this logic in someway up to where we process the bindings into prepared statements for SQL queries then we can remove the repetition and make it a more consistent rule. Where the type coercion function is called from should be a suitable place to carry out these checks. 

I know we've discussed this a few times before, but ideally I would love to schedule a call across teams to decide on some actual rules to follow in regards to what `null`, `undefined` and `""` mean when the frontend sends them up; it probably won't be the easiest fix, but it is obviously a massive source of bugs as I know @melohagan you've already raised a couple of edge case fixes around this.

**Comment by melohagan** [comment]
Thanks for taking a look guys! Will close this PR for now 👍

**Pull request closed without merging**
