### PR TITLE
Prevent users table from being used as a datasource

### PR DESCRIPTION
**Pull request by aptkingston**
## Description
This prevents the users table from being selected as a datasource in front end of client apps. The reasoning for this is that the users table is not a normal table and does not work with the normal front end components. Issue is detailed here https://github.com/Budibase/budibase/issues/921.

### CODE REVIEW

**Comment by shogunpurple** [comment]
@aptkingston Can we not allow the listing of users but just not their creation? That said, not sure how that would look UI wise

**Comment by aptkingston** [comment]
Afraid not, unless we do something hacky to handle roles. Roles aren't a real relationship field, so if we list users then the role will be displayed as an ID (which will be a long random ID for any new roles, and therefore not useful).

**Comment by aptkingston** [comment]
@joebudi pointed out there's still one other place I need to remove the option to use the users table, so this isn't ready to merge yet.

**Comment by aptkingston** [comment]
Think this is definitely stale at this stage. If we want to revisit something like this in future then that's fine because it's very quick to implement. I'll close this one for now.

**Pull request closed without merging**
