### PR TITLE
Misc fixes

### PR DESCRIPTION
**Pull request by aptkingston**
## Description
Collection of various fixes.

Fixes:
- Add validation to prevent changing a screen URL to an in-use URL #4840
image
- Add validation to prevent changing a screen role to one that is already in use for that URL #4840
image
- Fix UI not updating properly to display screen list when changing the role for a screen
- Fix flashing empty states when moving around home screen pages as we already have the required data
- Fix flashing of template pictures when loading templates list by just setting images that fail to load to `display: none` rather than defaulting to this state
- Pull in the latest global state context on each button action enrichment to allow for state updates made during the button action execution chain to be referenced by later actions #5212
- Disable validation for search fields used inside blocks #5223
- Update chart data labels to white #5199
image
- Update home screen sizes #5228
image
- Fix chart tooltip color and size
image
- Fix not resetting button action context on each execution of button actions #4962
- Update spectrum card word wrapping again to not break on words that don't need broken
- Fix endless encoding loop when entering screen URLs https://github.com/Budibase/budibase/issues/5291
- Fix issue with automations with no inputs in an app action trigger https://github.com/Budibase/budibase/issues/5300

### CODE REVIEW

**Review by shogunpurple — APPROVED** [review]
Great fixes here - I think we can probably get this one into `master` to be honest, and just have QA verify it in pre-prod.

**Comment by aptkingston** [comment]
Double checked there but can't just update the base branch since this was originally off develop so contains a bunch of other stuff. I guess cherry picking every individual commit into another branch based off master is the only other way?

**Comment by Rory-Powell** [comment]
> I guess cherry picking every individual commit into another branch based off master is the only other way?

Another method could be to checkout a copy of this branch `cheels-fixes-master` and run a `git rebase master` on that

**Comment by aptkingston** [comment]
Actually think I'd be more comfortable getting this into develop given the amount of changes here. Plus I think it would just lead to conflicts on develop with the other work going in this month.

**Pull request merged**
