### PR TITLE
Undo time offset

### PR DESCRIPTION
**Pull request by melohagan**
## Description
Time was being intentionally offset in the Date Picker code, but it's causing an unwanted affect.
@aptkingston Do you remember the scenario that was previously not working?

Addresses: 
- https://github.com/Budibase/budibase/issues/9138

bug

### CODE REVIEW

**Comment by aptkingston** [comment]
It was added for a reason - as commented in the code. Flatpickr was probably just ignoring timezone and always using daylight savings. Guessing it works fine with this removed now that the hour has changed?

**Comment by melohagan** [comment]
> It was added for a reason - as commented in the code. Flatpickr was probably just ignoring timezone and always using daylight savings. Guessing it works fine with this removed now that the hour has changed?

I did try setting the hour forward and backwards using the Time Shift plugin. Wasn't able to recreate the original issue described by the code comment.

**Comment by melohagan** [comment]
I tested the Date Picker on **1.2.2** and wasn't able to recreate the original issue (this version was before the original bug fix was added).

You can try it out on: http://singleimage.qa.budibase.net/

**Comment by aptkingston** [comment]
No problem, happy to remove this then! This bug will probably reappear when daylight savings ends again, but we can just keep toggling this until we remove the scourge that is flatpickr.

**Review by aptkingston — APPROVED** [review]

**Pull request merged**
