### PR TITLE
Feature/global user management

### PR DESCRIPTION
**Pull request by shogunpurple**
## Description
This PR revamps user authentication, and introduces the concept of a "global user" on the budibase platform". Users are authenticated against budibase as a whole, rather than a specific application.

### This PR Includes
- The introduction of a shared `@budibase/auth` library, that contains passport middleware, as well as anything else related to budibase users and cookies.
- Swapping over our current hand-rolled authentication to use passportJS.
- Updating our management of cookies so that there is a single cookie used to authenticate with all apps and the builder - this simply links to the global user.
- A separate `currentapp` cookie, that gets updated as you interact with BB apps. This contains your role for that specific app and some other app specific information
- requests to `/api/admin` are proxied directly to the worker service, which is now responsible for auth and for admin APIs
- Users are now divided into global users (who can login to the platform) and user "metadata" (per app). This is so users can have separate configuration at an app level, but anything that applies across apps is at the global level. 

### Demo
https://www.loom.com/share/2eef26dc05b54875b0c5c331ec7b4744

### What this means for you
- Initially, all users will be builders with complete access, with the goal of updating this to a list of apps that a user can access, for end usage and builder usage at a global level (stored in the global user database).
- You will have to log in to the builder. Once you do however, you will be authenticated for all your apps as well
- The app creation screen no longer contains the option to create a "first user" for the app. It will only ask you which role you want to assign to yourself in your newly created app.

### Caveats
- Since we don't have the admin UI yet, initially if you have no users, you must create a test user from the builder login screen. (Click the "create test user" button) This will create a user with the following creds:
```
username: test@test.com
password: test
```

### CODE REVIEW

**Comment by shogunpurple** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by mike12345567** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by mike12345567** [comment]
recheck

**Comment by shogunpurple** [comment]
recheck

**Comment by mike12345567** [comment]
Marty covered all of the points that this PR introduces very well, not much to add there! We've done a bit of re-factoring as well, just general cleanup of a lot of old auth functionality that was redundant.

Only thing I will expand on is the decision to have two encrypted cookies, this is something that was discussed with @aptkingston extensively, basically we have:
1. A global cookie `budibase:auth` which provides access to the platform but has no perms/roles info. This will however contain global information, for example if the user is a global builder (can access any builder app).
2. A app context cookie, `budibase:currentapp` which has information such as the role of the currently logged in user for the current app (as well as app ID incase a request doesn't provide the current app ID).

Keeping these two cookies separate means that we don't need to constantly expire and re-set the global cookie, it means that any time something changes we only have to change the cookie for the context of that change, generally the change will occur at either a global level or an app level, for example when the user changes between apps we expire the `currentapp` cookie and create a new one with the right app ID and their role in that app.

### Further steps
1. Expanding upon the functionality provided by the centralised system, so the ability to handle forgotten password flows and the likes.
2. API keys, now that everything is centralised we could provide access to the API via an API key, currently the webhook endpoints are unsecured because theres no nice way to provide access.
3. Handling stale data in the cookie, for example if the user's role is updated then it will persist in the `currentapp` cookie for the time being, timing out this cookie would be a good idea. We might do this by storing a `version` in each cookie which is generated against the global database, or app database and store this in Redis, each time a request is made the `auth` package could check the Redis instance to see if the version has changed since the cookie was generated, if it has then the cookie could be expired.
4.

**Review by aptkingston — APPROVED** [review]
Awesome work guys 🚀 Makes the current workflow so much smoother and sets the groundwork for the future admin panel. Looking forward to getting this in!

**Pull request merged**
