### PR TITLE
Layout tweaks

### PR DESCRIPTION
**Pull request by aptkingston**
## Description
I missed the PR yesterday with the initial layout stuff, so these changes are some tweaks to the overall layout to match designs better and allow full screen pages which we need.

Changes:
- Update borders to match designs
- Update background colours to correct spectrum colours
- Update padding to match designs
- Add `Page` layout component which can be optionally full-width. This should be used in all new pages.
- Allow full-width pages

Use the `Page` component to wrap new pages - I recommend adding it in `_layout.svelte` for portal pages which have mutliple screens (e.g. settings), or adding it directly in a route's `index.svelte` for single screen pages. `Page` has a `wide` prop for full-width, such as the app list screen.
```html
<script>
  import { Page } from "@budibase/bbui"
</script>

<Page>
  <slot />
</Page>
```

## Screenshots
The compression and small sizes don't represent the colours well - click on these screenshots to see them full screen properly.

Subtle changes to padding, borders and background colours:
image

Example of a full-width page:
image

### CODE REVIEW

**Review by shogunpurple — APPROVED** [review]
This is great - super useful for us going forward. 🚀

**Comment by joebudi** [comment]
This looks incredible.

2 things: 

- the label alignment is off with the switch component (send analytics...)
- bb/company icon is solid and the user icon is gradient - prob best to be consistent here.

**Comment by aptkingston** [comment]
> This looks incredible.
> 
> 2 things:
> 
> * the label alignment is off with the switch component (send analytics...)
> * bb/company icon is solid and the user icon is a gradient - prob best to be consistent here.

Yea I noticed the label too but I didn't implement that page or change it here, I just used it as a page example. It does need fixed though.

I'll make a solid user placeholder image, but both are just placeholders at the moment anyway.

**Comment by kevmodrome** [comment]
Get 'em merged in!

**Comment by kevmodrome** [comment]
> > This looks incredible.
> > 2 things:
> > 
> > * the label alignment is off with the switch component (send analytics...)
> > * bb/company icon is solid and the user icon is a gradient - prob best to be consistent here.
> 
> Yea I noticed the label too but I didn't implement that page or change it here, I just used it as a page example. It does need fixed though.
> 
> I'll make a solid user placeholder image, but both are just placeholders at the moment anyway.

I think we might need to adjust the Label component itself, I think that should fix the problem in most places where we have a label to the left and an input to the right.

**Pull request merged**
