### PR TITLE
Embedded Map V2

### PR DESCRIPTION
**Pull request by daawaan4x**
## Description

Addresses #5314. This overhauls the integration of the embedded map with GIS services together with a collection of changes with the previous embedded map

### GIS Integration Overhaul
 - Support multiple tile layers
 - Support multiple tile services (currently, the initial pull request only adds XYZ and WMS services)
 - Fine-grained access to Leaflet options
 - Support binding visibility of layers

### Changes/Fixes 
 - Marker-related features have been grouped into a section
 - Input for default zoom level has been changed from percentage numbering to the actual zoom level numbering since Leaflet doesn't zoom seamlessly anyway
 - Added configurable minimum and maximum zoom levels
 - Added On Click Map Action with Lat/Long parameters supplied
 - Configurable Attribution Prefix

## Screenshots

image

## Remarks

In relation to #5281, directly integrating private GIS services can't be supported at the moment since it would require those GIS services to have their own middleware for authenticating incoming requests. A solution would be to add a "REST API Proxy" data source in Budibase aside from the "REST API Connector" that proxies internal services to authenticate incoming requests so users won't have to go through the hassle of making their own middleware. Moreover, being able to proxy internal APIs will open a lot of room for customizability when developing apps with Budibase without the hassle of dealing with security

### CODE REVIEW

**Comment by daawaan** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by shogunpurple** [comment]
Hi @daawaan - first of all thank you for the contribution and taking the time!

I'm not quite sure what you meant by saying this PR addresses https://github.com/Budibase/budibase/issues/5314. That's an empty issue ticket that has not been specced yet, but will be over the next few months. It seems like this PR is a collection of changes that you needed specifically for your use case. 

Thanks for providing a detailed PR description showing all the changes you made, but In order for us to review this correctly and to understand if it's something we should merge for the wider community, It would be really good to hear a bit more about your exact use case/spec, why you made these changes and the things that this PR is able to allow you to do.

In the meantime, I should mention that we have a project board here with good issues for contributors:
https://github.com/Budibase/budibase/projects/22

We have discussed internally about external contributions, and we will be adding more docs to the README/CONTRIBUTING and labels to the tickets to guide external contributors.

Thanks 🙏

**Comment by daawaan** [comment]
Oh dear, I accidentally messed up this pull request

**Comment by daawaan** [comment]
I think I made a mess, is this still okay?

**Comment by daawaan** [comment]
Dear, I messed up this branch, Is this still okay?

**Comment by JayP718** [comment]
Hi, 

Just I'm new to github but I'm just trying to see where this commit is at. I think this feature would be great!

**Pull request closed without merging**
