### PR TITLE
Fix handling of the Postgres money field.

### PR DESCRIPTION
**Pull request by samwho**
## Description

In https://github.com/Budibase/budibase/pull/14861 I introduced a bug that broke our handling of the Postgres money field. We had no tests around this fields, so on top of fixing the bug I have also introduced new tests to prevent this happening again.

### CODE REVIEW

**Review by mike12345567 — APPROVED** [review]
LGTM!

**Review by shogunpurple — APPROVED** [review]
LGTM

**Review by melohagan — APPROVED** [review]
LGTM - Just wondering what would happen if you tried to update a money field with three decimal places, e.g. `"200.123" ?

**Comment by samwho** [comment]
@melohagan 

CleanShot 2024-10-31 at 14 41 23@2x

I'm uncertain if this is the correct behaviour or not.

**Review by adrinr — APPROVED** [review]
💸

**Pull request merged**
