### PR TITLE
App Theme binding added

### PR DESCRIPTION
**Pull request by deanhannigan**
## Description

Added a new binding, `{{App.Theme}}` to the `Device` binding category. 

All currently supported themes will be prefixed by `spectrum--`

Addresses: 
-  https://github.com/Budibase/budibase/issues/11409

## Screenshots

The binding can be found in the Device section in the binding drawer.

Screenshot 2023-08-30 at 09 28 43

Updating when the theme is changed

bindings

### CODE REVIEW

**Review by melohagan — APPROVED** [review]
LGTM! The only thought I have is if *Device* is the correct category for the binding?

I.e. if the theme comes from the Budibase app. Don't want to give the impression that the theme comes from the device itself?

**Comment by aptkingston** [comment]
> LGTM! The only thought I have is if _Device_ is the correct category for the binding?
> 
> I.e. if the theme comes from the Budibase app. Don't want to give the impression that the theme comes from the device itself?

We decided on device just because it was the closest matching category we have. If we add more "app" level stuff down the line then I'd definitely break this out into a new dedicated catergory, but it felt unnecessary to create a new category for one binding.

The readable binding is also `App.Theme` to attempt to help with this.

**Comment by aptkingston** [comment]
@deanhannigan is this ready to review? It's marked as a draft at the moment.

**Review by aptkingston — APPROVED** [review]
LGTM!

**Pull request merged**
