### PR TITLE
use _id instead of name for identifying tables

### LINKED ISSUE #4809: Unable to select table when another table with the same name exists
**Describe the bug**
When you have two data connections, each with a table called 'products', both table get selected when adding a new screen

**To Reproduce**
1. Go to the Data tab.
2. Create two data connections, each with a table called 'Products' (or any other name, as long as they are the same)
3. Go to the design tab and click the 'add' button
4. Try selecting one of the 'Products' tables.
5. Notice: Both tables get selected
6. Click the Add Screens button
7. 6 screens are added

**Expected behavior**
A single table should become selected and 3 screens should be created

**Screenshots**
image

image

**Desktop (please complete the following information):**
 - OS: MacOS 12.2.1
 - Browser: Vivaldi
 - Version: develop branch

### PR DESCRIPTION
**Pull request by mslourens**
## Description
When you have two data sources with a table with the same name, you cannot select one of the two tables when creating a new screen, you'll always select all, because the table is identified by name, not by _id. This PR fixes that.
Fixes #4809

## Screenshots
image

### CODE REVIEW

**Review by shogunpurple — APPROVED** [review]
LGTM!

**Review by aptkingston — APPROVED** [review]
Thanks @mslourens!

**Comment by aptkingston** [comment]
@mslourens could you pull in develop to this branch and update it so that the tests will pass and we can get this merged? Thanks!

**Comment by aptkingston** [comment]
I'm closing this in favour of https://github.com/Budibase/budibase/pull/6352, as this PR has got stale and now has conflicts due to new work. I've credited you in the new PR as well @mslourens to highlight that you had originally addressed this issue. Thanks again!

**Pull request closed without merging**
