### PR TITLE
Add typescript to worker project

### LINKED ISSUE #4003: Add typescript support to worker
**Description**
Add typescript support to worker to be consistent with the server. 
For details on adding TS support see: https://www.typescriptlang.org/docs/handbook/declaration-files/dts-from-js.html

### PR DESCRIPTION
**Pull request by mslourens**
## Description
Fixes #4003 - Adds typescript support to the worker project

### CODE REVIEW

**Comment by mslourens** [comment]
I am not sure why the tests fail, because I didn't change actual code, just added typescript and changed the index.js to index.ts. The error message is quite cryptic, but after some debugging I found the actual error:
```
Error: getaddrinfo ENOTFOUND smtptesthost.com
        at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26)
        at GetAddrInfoReqWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
      errno: -3008,
      code: 'EDNS',
      syscall: 'getaddrinfo',
      hostname: 'smtptesthost.com',
      command: 'CONN'
    }
```
which is caused by the line `await config.saveSmtpConfig()` in `getScopedFullConfig`. I tried to compare develop with my branch but didn't see any changes that could cause this error. 

Any help is appreciated.

**Comment by Rory-Powell** [comment]
@mslourens found the issues with the tests, it was to do with changes in how jest mock statements are hoisted when using typescript. The fix has been pushed to your branch. For more context see: https://github.com/kulshekhar/ts-jest/issues/90#issuecomment-277632488

**Review by Rory-Powell — APPROVED** [review]
LGTM 👍

**Comment by mslourens** [comment]
@Rory-Powell thanks for your help. Somehow I had to build the app before running the e2e tests, it seemed some old version was still being used. Now the tests are green again and we can merge this PR.

**Comment by Rory-Powell** [comment]
Good call out on the need to build, we had a discussion around this recently and a fix has been added in this PR already
https://github.com/Budibase/budibase/pull/4276/files#diff-a549d2657aa3ea787f685c405385a2c352488058096cb3c4d68a4ab82bf3bf50 so I've just reverted the `precy:ci"` command in this PR

**Pull request merged**
