### PR TITLE
Fix release single image CI

### PR DESCRIPTION
**Pull request by Max-42**
Trying to fix https://github.com/Budibase/budibase/actions/runs/4798193920

this should fix [release-singleimage.yml](https://github.com/Budibase/budibase/blob/develop/.github/workflows/release-singleimage.yml) because

## Description
_The Problem is that the Workflow fails, and therefore is not pushed to the DockerHub_

Addresses: 
- `<Enter the Link to the issue(s) this PR addresses>` (sorry, did not create an issue first.)
- [blog about similar issue](https://the-codeslinger.com/2020/03/26/debian-bullseye-the-repository-does-not-have-a-release-file/)
- [Question to the error thrown by the workflow (not by me)](https://serverfault.com/questions/1074688/security-debian-org-does-not-have-a-release-file-on-with-debian-docker-images)

## Screenshots
_Picture of run_

## Documentation
- before re-running the Action, a `yarn publish:docker:couch` is required to apply the changes by pushing the CouchDB image to the DockerHub because [this Dockerfile](https://github.com/Budibase/budibase/blob/develop/hosting/single/Dockerfile) is based on the Image
- [x] I have reviewed the budibase documentation to verify if this feature requires any changes. If changes or new docs are required, I have written them.

I have read the CLA Document and I hereby sign the CLA

### CODE REVIEW

**Comment by Max-42** [comment]
recheck

**Comment by Max-42** [comment]
recheck

**Comment by Max-42** [comment]
I forgot to mention, I additionally changed the Java version from `openjdk-8-jre` to `openjdk-11-jre `because openjdk-8-jre is no longer included in apt.

**Comment by mike12345567** [comment]
> I forgot to mention, I additionally changed the Java version from `openjdk-8-jre` to `openjdk-11-jre `because openjdk-8-jre is no longer included in apt.

Hi @Max-42 - on this - the image needs to use OpenJDK 8 - as are the requirements of Clouseau our Lucene search engine.
https://docs.couchdb.org/en/stable/install/search.html

**Comment by Max-42** [comment]
> > I forgot to mention, I additionally changed the Java version from `openjdk-8-jre` to `openjdk-11-jre `because openjdk-8-jre is no longer included in apt.
> 
> Hi @Max-42 - on this - the image needs to use OpenJDK/JRE 8 - as are the requirements of Clouseau our Lucene search engine. https://docs.couchdb.org/en/stable/install/search.html

Okay, I have tried it without, but then the CI won't build because openjdk-8-jdk packages had been removed from apt (https://serverfault.com/questions/974992/why-isnt-there-a-openjdk-8-jdk-package-on-debian-anymore)

**Comment by Max-42** [comment]
@shogunpurple I saw that https://github.com/Budibase/budibase/actions/runs/4874006390/jobs/8694373860 failed, did you run a `yarn publish:docker:couch` manual after build because it seems that the CI does not push the image CouchDB to the DockerHub.

**Comment by Max-42** [comment]
Sadly I noticed that now my builds are failing even locally. I think my pull request could be invalid/incomplete I have to look in it when I am home.

**Comment by Max-42** [comment]
I will close this because the [last run] (https://github.com/Budibase/budibase/actions/runs/4876532104/jobs/8700143706) passed.

Thanks!

**Pull request closed without merging**
