### PR TITLE
Form fixes

### LINKED ISSUE #1580: Required bool field errors on record save
**Describe the bug**
When saving a record inside my app, if I do not complete a required bool field an exception is thrown and my record is not saved

**To Reproduce**
1. Create required boolean field
2. Add field to a form on Create Record
3. Preview the app
4. Create new record - don't touch the checkbox!
5. Save record

RESULT
Record validates correctly, Screen navigates back to list screen, but error banner appears. Record is not saved

EXPECTED
Actually, I'm not sure...

Is it right that a validation message should appear? If you want the checkbox the remain unchecked, then you must check and uncheck

Maybe it makes no sense for a boolean field to be required? It should default to `false` always?

Or do we need a tri-state checkbox, that has a true, false and  Nothing state?

### PR DESCRIPTION
**Pull request by aptkingston**
## Description
This PR addresses a couple of form issues which currently exist that prevent some fundamental functionality such as being able to add related data to a row that's inside a data provider.

- Field initial values are now correctly registered on mount, which means running validate is no longer mandatory in order for fields to have a value after mounting the form. This prevents rare errors where no values were being sent up if fields were not changed.
- Forms have a new setting to specify if they are for creating or updating rows. This setting is needed so that the form knows whether or not to inherit initial values from a parent data context. This determination of initial values has also been improved to be more strict, and ensure that only contexts of the same table are inherited.
- Unrelated, but I've updated the string templates library to allow processing of `null` rather than throw an error, as this is sometimes the case when called from client library contexts.

**This PR requires migration if pulled into exisiting apps.**
**All exisiting forms which update data need to be updated to specify the "Update" type setting, otherwise they will not have initial values and will function as if they are creating new rows.**
There won't be any crashes or errors - they'll just function as "Create" forms rather than "Update".

Since there is currently no client library upgrade strategy this will not affect customers - only dev environments where the client version is always updated.

Closes https://github.com/Budibase/budibase/issues/1580.

### CODE REVIEW

**Review by kevmodrome — APPROVED** [review]
LGTM

**Review by shogunpurple — APPROVED** [review]
LGTM 🚀 Not too worried about the migration given they just need to enable a setting and it won't crash the app.

**Comment by mike12345567** [comment]
LGTM! Nice method, the SQL work will require specifying if it is an update or a create so this will work well!

**Comment by joebudi** [comment]
@aptkingston and @mjashanks we should raise a discussion around this notifying the community of the form-breaking change.

**Comment by aptkingston** [comment]
> 
> 
> @aptkingston and @mjashanks we should raise a discussion around this notifying the community of the form-breaking change.

We can, but like I said it's impossible for users to update their client library versions at the moment anyway so no one will see this issue unless they did something like export and import their app again. We should add it to the form docs though, so users know it's a thing for new apps.

**Comment by aptkingston** [comment]
> 
> 
> Can #1581 be closed also?

Don't think so, since that's the backend - in order to solve that we need to probably update lucene indexing so that `null` in bool fields is indexed to `false`. We can send up `false` as an initial value from the backend UI too, but that's not enough because if you add a bool column to a table with exising rows they all won't have the bool property defined. So I think updating lucene indexing is the best way to go. I can look in to that separately and update it in that issue,

**Pull request merged**
