### PR TITLE
Integration of Backend Models / Views with Data Driven Components

### PR DESCRIPTION
**Pull request by Conor-Mack**
- Created a model / view select component and added to the settings panel
- Created model view field option select so that the user can choose which field they want to target (this was previously an input for charts which was difficult to work with).
- Added `dependsOn` key to panel structure so that controls can be show / hidden depending on whether another property has been assigned or not
- Created function for easy data fetching of model / view data from data driven components
- Set up backend data fetching to data driven components (all charts, list and datatable)

image

### CODE REVIEW

**Comment by joebudi** [comment]
Hey @Conor-Mack 

Suggestions:

Don't use the term model in the frontend. I would have the select placement text as Table / View.
The design is not consistent with the other inputs in the settings panel. It should have the grey background, no border - http://bbui.budibase.com/Form/Select?view=secondary&fs=0&c&o=0&p&cv=%40none&bg=%23fff . I see you've used a button for this. Was there a reason for this?

Within a view, there are 3 functions; filter, calculate, group.
Filter works great. Group works great. All together, they work great. But for some reason, calculate when used by itself, or with one of the others does not work great.
https://www.loom.com/share/9b1b00fe00e14465b77391c3864249af



Also, with charts, when attempted to

**Comment by Conor-Mack** [comment]
Hey Joe,

Re the design, I built the ModelViewSelect to resemble the image within the [initial issue](https://github.com/Budibase/budibase/issues/546) (see the image in martins comment). Note: theres some inconsistencies between the font in the image in the issue and the dropdown menu (image in my first comment). It would be good to hear your opinion on how I could style to make it them more alike.

The ModelViewSelect is a bit different to the other OptionSelects used elsewhere in the Design / Settings Panel in that its a Dropdown menu with an anchor. I figured it best to make use of what we have in BBUI already instead of creating a similar control from scratch in the builder. Do we have anything within BBUI that you would recommend using in order to keep a consistent style with other controls? 

If your running into any bugs with the charts let me know and I'll get them fixed up

**Comment by joebudi** [comment]
Hey

Can we not use the [select component](http://bbui.budibase.com/Form/Select?view=secondary&fs=0&c&o=0&p&cv=%40none&bg=%23fff) instead of the button ModelViewSelect button?

**Comment by Conor-Mack** [comment]
It wouldn't really work for this use case because it doesn't allow us to partition models and views under separate headings and sections

**Comment by joebudi** [comment]
After a call with Conor, we agreed to leave the styling for now.
One of the key issues, is it is not possible to calculate a view, and display a number, such as sum, in the frontend.

**Comment by Conor-Mack** [comment]
@joebudi my most recent commit under this PR should fix the single calculation issue you were experiencing

The group column was shown in the schema whenever no group by operation had been set on a view. This seems unnecessary as it only displayed a null value.
 
This commit separates out group and field properties and switches them in and out of the schema depending on whether a calculation alone or a calculation and groupby has been set. This means we get single calculation views based on a field whenever no group by has been set.

Appending to this PR as it was necessary to change some of the data fetching logic I did for data driven components to fit in with this change.

**Review by shogunpurple — APPROVED** [review]
LGTM, nice work.

**Pull request merged**
