### PR TITLE
Add Pagination Title

### PR DESCRIPTION
**Pull request by carmas123**
## Description
Added the ability to change "Page" label into pagination of Data Provider

### CODE REVIEW

**Comment by carmas123** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by shogunpurple** [comment]
@carmas123 can you re-raise this into our main branch `master` please?

**Comment by carmas123** [comment]
done

**Comment by shogunpurple** [comment]
@carmas123 seems like a weird diff now as it's off `develop` - it would be easier to branch of `master`, make your changes and create a new PR if possible

**Pull request closed without merging**
