### PR TITLE
Fixes for some recent issues

### LINKED ISSUE #1862: BB App is in loading loop
**Describe the bug**
When a user with role PUBLIC logs in and opens an application, the browser is constantly reloading. Rights are set properly in the platform and in the app.
Administrative or developer users can login and use the app. Even without the dev_ part of the url.
The bb plattform is reachable and a login is possible.
Server OS is an up-to-date Ubuntu 20.04.2 LTS

**To Reproduce**
1. Open Browser
2. point to bb app url
3. Login with a User with BASIC Role 
4. Site will load over and over again

**Expected behavior**
Show the app

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser Safari / Crome / Firefox / Edge

**Additional context**

### LINKED ISSUE #1931: Date filtering doesn't work since recent work on HBS enrichment removed date post-processing
As part of the recent work on optimising HBS enrichment, we removed the recursive function which used to go though context and transform date objects into ISO strings. A consequence of this is that HBS now enriches date objects with just a `toString()` meaning they get transformed into something like `Wed Jul 16 2014 12:00:00 GMT+0100 (British Summer Time)` instead of `2014-07-16T11:00:00.000Z`. 

This format is not compatible with Lucene searching, so currently doing any filtering on a `datetime` field will return 0 results.

This fix for this is simply parsing the data in data providers for any `datetime` fields and building the lucene query with ISO strings like before.

### PR DESCRIPTION
**Pull request by aptkingston**
## Description
This is a couple of fixes to address recent bugs raised in discussions and issues.

- Fix https://github.com/Budibase/budibase/issues/1931
Fix filtering data providers using `datetime` fields.
- Address https://github.com/Budibase/budibase/discussions/1927
Fix tables showing "No rows" until clicked on. This was actually nothing to do with tables, but actually a consequence of the multiple 409 update conflicts that we experience in the builder. I have updated the filter editor of data providers to reduce unecessary updates, and therefore unecessary 409s, which fixes this issue with tables. It's been around for a while and bugged me too. The core problem was that the call to set the initial data provider setting on the table was pretty much guaranteed to 409.
- Fix component selection being reset on page refresh. This has driven me crazy for a while, because I spent a fair bit of time ensuring we had proper synchronisation of URL and component selection state. The issue was with the `Tabs` BBUI component, because it was broadcasting a change event on mount, meaning the builder would reset you back to the first screen on every page reload. This also fixes the other mystery I've seen where sometimes the screen you have selected would change when you reload the page.
- Fix https://github.com/Budibase/budibase/issues/1862 and https://github.com/Budibase/budibase/discussions/1929
 Fix loading loop when logging in as a user with a PUBLIC role. The PUBLIC role has been removed because it does not make sense to have an authenticated user who is PUBLIC. By definition, an authenticated user is BASIC. All users now have access to all apps by default without 403 errors due to their default BASIC role. PUBLIC is reserved for unathenticated users. Thanks to @shogunpurple for implementing this.
- Client apps will not reload the page on receiving a 403, but will display an error saying your session may have expired.
- Error fallback added to real client apps so that if the app fails to load the budibase client a useful error message will be displayed instead of a blank white screen.
- Client apps will not try to enrich the user object when the role is PUBLIC, avoiding a 403
- Client apps will redirect users to any available screens if they do not have permission to view the current screen
- Client apps will redirect to login whenever the user is not logged in
- Client apps will show an error message when the user is logged in but cannot use an app
image

### CODE REVIEW

**Comment by mike12345567** [comment]
Theres some great fixes here, the 409 is an issue we'll need to deal with at some point, realistically the builder should at minimum for screens and layouts fetch them again if it 409s and try the request again with the new `_rev` although this could be difficult to handle as the fact there is a 409 means that whatever the builder has in the store for screen is not actually what the server has, so could accidentally overwrite some other previous change.

I've started working on the session issue so that what the 403 redirect was trying to achieve shouldn't be as necessary anymore.

My only concern is making everyone logged in `BASIC` in every app, this means that its impossible to actually revoke someones access to an app, as a default it really defeats the purpose of groups - everyone always has access and its kind of difficult to revoke it, only grant higher access levels, like making people administrators. I feel like as a default every user having access to all apps is just very dangerous.

**Comment by shogunpurple** [comment]
@mike12345567 I think the 409 thing we should just paper over with some error message - like a notification with a refresh button to fetch again, perhaps. I'm not sure we can totally avoid it without doing full sync or fetch before write, as you say.

With BASIC permissions - the issue here was not just semantic (PUBLIC should not ever mean logged in/be configurable, it's confusing) but groups are the core way that users will control user access to budibase applications. As part of the groups work, we have also accounted for the ability to ban a user from an app, which will take precedence before any of the other roles or group allocations.

Assigning BASIC access to an internal user who the admin/group admin has invited into the organisation makes sense - they will have BASIC access to the public apps in your org, and any apps that are in a group they won't see, unless added to that group. Since we provide one group by default, the common pattern will probably be a "private" group, and the rest are public. This encourages group creation - which as we know is pretty important!

**Comment by mike12345567** [comment]
> @mike12345567 I think the 409 thing we should just paper over with some error message - like a notification with a refresh button to fetch again, perhaps. I'm not sure we can totally avoid it without doing full sync or fetch before write, as you say.
> 
> With BASIC permissions - the issue here was not just semantic (PUBLIC should not ever mean logged in/be configurable, it's confusing) but groups are the core way that users will control user access to budibase applications. As part of the groups work, we have also accounted for the ability to ban a user from an app, which will take precedence before any of the other roles or group allocations.
> 
> Assigning BASIC access to an internal user who the admin/group admin has invited into the organisation makes sense - they will have BASIC access to the public apps in your org, and any apps that are in a group they won't see, unless added to that group. Since we provide one group by default, the common pattern will probably be a "private" group, and the rest are public. This encourages group creation - which as we know is pretty important!

Yeah for the 409 thats probably all we can do, I expect its probably something to do with a race condition, like two screen updates at the same time one goes ahead, one fails.

I see, this makes a bit more sense then, so in this group design you aren't in a group that gives you access to the private app, so while you might have a role for that app that would let you access it, the fact you're not in a group for it blocks your access. I'll need to think about how to handle this now as it means a bit of a change to the middlewares, as I had thought that every user by default wouldn't have any access and then they would be granted access by the groups, whereas now its a bit more of the inverse, every user has access to everything, but we need to block them from doing anything to "private" apps - e.g. ones that they don't have access to as they are in a group that the user is not part of. I think the inversion of logic here might still be a bit dangerous as its switching from a white list approach to a black list approach but it'll be possible to make it work.

**Comment by shogunpurple** [comment]
> I see, this makes a bit more sense then, so in this group design you aren't in a group that gives you access to the private app, so while you might have a role for that app that would let you access it, the fact you're not in a group for it blocks your access. I'll need to think about how to handle this now as it means a bit of a change to the middlewares, as I had thought that every user by default wouldn't have any access and then they would be granted access by the groups, whereas now its a bit more of the inverse, every user has access to everything, but we need to block them from doing anything to "private" apps - e.g. ones that they don't have access to as they are in a group that the user is not part of. I think the inversion of logic here might still be a bit dangerous as its switching from a white list approach to a black list approach but it'll be possible to make it work.

From the design doc we put together the other day:
```
Requirements
- Admins can create new groups in a budibase installation
- Admin can assign group admins to the group
- Every group can have one or more group admins, you can set group admins at group creation time
- A group admin can add/remove people from the group. 
- A group admin can invite users outside budibase into their group. When they join, they are assigned to the group only
- Apps are still public by default, but apps that are assigned to groups are private unless you are in that group
- If you are in multiple groups, when you create an app, you can choose which groups that app is in
- Only global builder can create totally public apps
- Group admins can assign group roles for apps.
- Group admins can set individual user roles for apps in their group.

Roles Flow
- User logs into an app
- Budibase checks if they have a user role. This is the highest specificity, so user role will be used straight away if defined
- If no user role, check if there is a group role defined for the application. If, so use that.
```

I've noticed that the actual github issue for groups hasn't been updated with this info since the design doc was put together - I've updated it there in zenhub and assigned it. If you aren't in a group, you basically aren't aware that the app even exists - you won't see it in your portal and you can't access it.  The reason for the lean on groups is that by using the just the standard RBAC roles with a private-by-default setup, you could essentially circumvent groups altogether.

**Comment by mike12345567** [comment]
Makes sense, I had been thinking of using roles to actually drive the underlying functionality of groups, but by making the middlewares group aware I think we can achieve the same functionality, think might cache the full list of groups and then lookup the groups on every API call, look through it and see if the user should have access to an app that way it can be restricted again.

**Review by mike12345567 — APPROVED** [review]
LGTM!

**Pull request merged**
