### PR TITLE
Replacing User IDs (from emails)

### PR DESCRIPTION
**Pull request by mike12345567**
## Description
It was suggested by the community that using emails as our user IDs maybe a mistake as it means when the user email address has to change we must change the user ID also.

This update is pretty much entirely internal, with a few changes which impacted the builder:
1. adding a `api/users/metadata/self` POST call which updates the current user; simplifying the user create/update calls
2. adding a `api/admin/users/first` call to the worker which creates the first user without the need for auth

Apart from this most of the work was refactoring anything that depended on the ID being an email address, the system now creates the global user first and then bases the metadata ID on the global ID, this means that it is easy to look up the global user from the metadata by just reversing the ID generation process.

### CODE REVIEW

**Review by shogunpurple — APPROVED** [review]
Great job - this makes way more sense 👍

**Comment by joebudi** [comment]
This is awesome. As a budibase developer, is it possible to set up my auth to accept user names, rather than emails now? This was a request from a user who informed me a lot of the employees at his workplace are shift/factory workers who do not have an email.

**Comment by mike12345567** [comment]
> This is awesome. As a budibase developer, is it possible to set up my auth to accept user names, rather than emails now? This was a request from a user who informed me a lot of the employees at his workplace are shift/factory workers who do not have an email.

Right now this is essentially identical to the way the system worked before in terms of signing in/password and so on, but we could easily change it from email to username, the only problem is that if there is no email attached to the user then everything we implement around forgotten passwords etc, invitations, which are based on email won't actually work. Realistically there are a two options we could do here:
1. Allow email only - this means that everything we do around SMTP will always be safe/work.
2. Allow anything as a username and an email - in this case you'd have the username and optionally an email specified. You might specify something at a global level saying that the username is always the email address or the form factor of the username. In this example you'd have to assume that a user might not have an email which would have implications on the SMTP work.

**Comment by joebudi** [comment]
Hey @mike12345567 . Yes, I was thinking more around point two. It's probably something to think about down the line, but probably not for now.

**Comment by mike12345567** [comment]
> Hey @mike12345567 . Yes, I was thinking more around point two. It's probably something to think about down the line, but probably not for now.

Yes, wouldn't be difficult to do honestly, would just mean changing some UI and the likes, just about managing everything without an email.

**Pull request merged**
