### PR TITLE
External datasource id filtering

### PR DESCRIPTION
**Pull request by melohagan**
## Description
Removed **_id** filtering for external DBs.

Addresses: 
- https://github.com/Budibase/budibase/issues/8334

Screenshots:
**External DB**
Screenshot 2022-11-29 at 11 02 19

**Internal DB**
Screenshot 2022-11-29 at 11 02 37

### CODE REVIEW

**Review by mike12345567 — COMMENTED** [review]
Could this cause issues with internal tables? We shouldn't allow filtering on `_id` externally, but its possible this is a feature people are utilising for internal tables as it will work.

**Review by shogunpurple — APPROVED** [review]
LGTM!

**Comment by melohagan** [comment]
> Could this cause issues with internal tables? We shouldn't allow filtering on `_id` externally, but its possible this is a feature people are utilising for internal tables as it will work.

As discussed, removed the **_id** field from filtering external DBs.

**Review by mike12345567 — APPROVED** [review]
LGTM

**Pull request merged**
