### PR TITLE
Fix eslint, update eslint and prettier versions and update package scripts

### PR DESCRIPTION
**Pull request by aptkingston**
## Description
This addresses the couple of issues which we current have in the project when using eslint and prettier.

Currently eslint does not actually correctly process any `.svelte` files. This means that our IDE's have also not been correctly detecting issues and there's a whole load of linting issues which we've missed. The inclusion of `eslint-plugin-prettier` does not play nicely with Svelte either, causing Webstorm and other editors to throw errors when trying to run eslint at all.

I've adjusted the configs to provide a correctly working implementation of both eslint and prettier which works in editors. It also now correctly lints `.svelte` files, which has revealed a big pile of stuff we need to fix. I have not fixed all those errors yet so this PR will fail, but I want to just highlight the config changes for now.

I've also adjusted the top level npm scripts so that there are just 2 scripts which should be ran `lint` and `lint:fix` (`format` has been removed). `lint` will run `eslint` and `prettier --check` over everything, and fail if there are issues with either, but it won't change any files - it's purely a lint check. `lint:fix` will run `eslint --fix` and `prettier --write` to attempt to fix any eslint errors and format the code with prettier. Happy for anyone to give feedback if you'd rather use different script names, but I think those are reasonably explicit.

## Screenshots
Here's out current eslint output, showing no issues:
before-lint

Here's the eslint output after this PR, now showing loads of issues in `.svelte` files which have gone undetected so far:
after-lint

Here's webstorm currently, unable to run eslint which has led to me having to disable eslint from the IDE:
before-webstorm

Here's webstorm after this PR, correctly highlighting eslint issues:
after-webstorm

### CODE REVIEW

**Comment by aptkingston** [comment]
Once you guys have had a chance to look at this, I'll actually fix all those eslint issues in this branch and I won't merge it until they're all sorted. Just keeping the diff clean for now until you've had a chance to take a look.

**Comment by mike12345567** [comment]
Wow, didn't realise that we hadn't been linting at all, that has revealed a fair number of issues!

If you need help going through them happy to jump on board and try and get them sorted.

In terms of the script names, I think we need the `lint:fix` to run the linter fixes as well, but I do think it would still be good to have a way to just run the formatter, sometimes I just want to write a bunch of stuff and run the formatter to fix it, which I would have previously done with `yarn format` - although don't particularly care what this is called, just that there is a way to run prettier separately to eslint fixes.

**Comment by aptkingston** [comment]
> 
> 
> Wow, didn't realise that we hadn't been linting at all, that has revealed a fair number of issues!
> 
> If you need help going through them happy to jump on board and try and get them sorted.
> 
> In terms of the script names, I think we need the `lint:fix` to run the linter fixes as well, but I do think it would still be good to have a way to just run the formatter, sometimes I just want to write a bunch of stuff and run the formatter to fix it, which I would have previously done with `yarn format` - although don't particularly care what this is called, just that there is a way to run prettier separately to eslint fixes.

Yea I've implemented custom `lint:fix:prettier` and `lint:fix:eslint` which `lint:fix` both calls through to, so you can still run it separately if you want but I don't think there's a downside to having eslint check at the same time as format, since a PR won't pass unless both of those pass. I might make prettier run first though, so you can `lint:fix` and an unused variable or something won't cause it to abandon early and not do the prettier formatting.

**Comment by mike12345567** [comment]
Yeah, I think that makes sense, always run prettier first as it shouldn't ever fail, whereas the linting might stop the formatting from running.

Yeah, I used to run prettier on save, but I like just writing my code until I'm happy with it then running the format on it, running it on save just threw me off from time to time!

**Review by mike12345567 — APPROVED** [review]

**Comment by aptkingston** [comment]
> 
> 
> Yeah, I think that makes sense, always run prettier first as it shouldn't ever fail, whereas the linting might stop the formatting from running.
> 
> Yeah, I used to run prettier on save, but I like just writing my code until I'm happy with it then running the format on it, running it on save just threw me off from time to time!

lol gotta ignore that 80 char limit as long as possible

**Review by shogunpurple — APPROVED** [review]
Great work! I also did not realise we were having these issues, it had got to the point I just thought that everything was linting beautifully 😂 

Nice to get this in.

**Comment by aptkingston** [comment]
Sweet, I'll get to work on cleaning everything up and I'll merge this when it's passing.

**Comment by shogunpurple** [comment]
@aptkingston Yeah, I think with things like this it's good to rip the plaster off as the branch goes stale almost instantly if we leave it. I can also chip in on the issues here if that's helpful

**Comment by aptkingston** [comment]
> 
> 
> @aptkingston Yeah, I think with things like this it's good to rip the plaster off as the branch goes stale almost instantly if we leave it. I can also chip in on the issues here if that's helpful

Think 90% of the issues are just unused variables etc but I'll give you guys a shout if it's something I'm not sure of. Cheers.

**Pull request merged**
