### PR TITLE
fixes link component being broken if the Url setting is left empty

### PR DESCRIPTION
**Pull request by kevmodrome**
## Description
Small fix to the Link component that stops it from crashing if you don't enter a url

### CODE REVIEW

**Review by shogunpurple — APPROVED** [review]
LGTM

**Comment by kevmodrome** [comment]
Not sure why this fails, doesn't look like it has anything to do with what I updated 🤔

**Comment by aptkingston** [comment]
Could be a random one.. maybe re run it? I also fixed this on my branch haha - good catch.

**Comment by kevmodrome** [comment]
Closing since it's fixed on another brnach

**Pull request closed without merging**
