### PR TITLE
REST query bindings for Current User

### LINKED ISSUE #6366: REST API Query - raw XML body not parsing correctly.
**Describe the bug**

Raw XML body text is failing to parse correctly resulting in a malformed body being sent to external REST APIs.

Sample raw XML content:
```
<?xml version="1.0" encoding="UTF-8"?>
<note>
  <email>{{Current User.email}}</email> 
  <code>1234</code>
  <ref>6789</ref>
  <somestring>{{sample_binding}}</somestring>
</note>
```

Sample content as it is sent to an external API:
```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>\n<root/>
```

**To Reproduce**

1. Create a rest datasource
2. Click 'Add query' and set the action to 'POST'
3. Update the API endpoint, click on the 'Body' tab and select the 'raw (XML)' option
4. Enter some valid sample content and send out a test request.
5. A consuming API will see one empty 'root' node in the body

**Expected behavior**

Entering valid XML markup should produce equally valid markup with any expressions properly rendered.

### PR DESCRIPTION
**Pull request by deanhannigan**
## Description
Allows the binding of information relating to the user in REST datasource requests. At runtime, the binding expressions will be replaced with information derived from the authenticated user initiating the request.

Addresses: https://github.com/Budibase/budibase/issues/3884
Fixes: https://github.com/Budibase/budibase/issues/6366

Available values: 
`_id, email, firstName, lastName, roleId, status, _rev`

Usage:
Add one of the above keys to a 'Current User' binding expression and place them into the REST datasource configuration.
- e.g. `{{Current User.email}}`

OAuthToken:
The oAuth2 token has been exposed with the following mapping: `{{Current User.OAuthToken}}`.  The mapping is also listed as an option when configuring `bearer` token authentication for a REST datasource.

The bindings can be used when configuring:
- Datasource Headers
- Request Bindings
- Request Parameters
- Request Headers
- Request Body

Binding updates:
The binding drawer has been added to expose all available bindings when configuring a rest query. These were previously available, but they are now listed in the binding drawer and have been assigned their own descriptive format.

- Query level bindings -> `{{Binding.myQueryBinding}}`. 
- Datasource static variables -> `{{Datasource.static.apiGroup}}`. Static variables exposed from the REST datasource
- Dynamic variables -> `{{Dynamic.etag}}` -> Dynamic variables built by the query.

**Note:** You do not have to explicitly use these formats when declaring your bindings. This format is automatically applied to make it easier to visualise a binding in the context it is being used. For example, `{{Binding.myQueryBinding}}` is still saved as `myQueryBinding` in the database.

## Screenshots

**Datasource Headers**
query_headers

**Datasource Authentication**
datasource_bearer

**Request Bindings**
bindings

**Request Parameters**
query_params

**Request Headers**
query_headers

**Request Body**
You can mix and match request parameters and user bindings in the body of your requests.
query_body

**Builder Provider Binding**
You can override the elements in your data providers in the builder itself.
builder_mapping

### CODE REVIEW

**Comment by ashwamegh** [comment]
@deanhannigan Does this also adds Logged in user contexts in Automations. So alongside `Triggers` data, we can also access` Current User` data?

**Comment by deanhannigan** [comment]
Hey @ashwamegh! This ticket focuses on adding Current User bindings to REST datasource queries. There's more information and further discussion around extending the functionality to automations here: https://github.com/Budibase/budibase/issues/4139

**Comment by deanhannigan** [comment]
@aptkingston Thanks for taking a look! Regarding the bindings, that's correct, they are enriched from a global user. 
Also yes, the `userBindings` are those currently exposed in the builder. My assumption was that this would mean parity between the builder and rest queries, but as you point out, for advanced functionality this could be rather limiting. 
To that end, should a specific set of bindings be created explicitly for the global user? Utilising the same syntax `{{ Current User.[query]}}` but a set of context specific bindings?

Some of the elements on the global user have nested elements like `oauth2.accessToken` or `thirdPartyProfile`. There is currently a suggestion to specifically add {{ OAuthToken }} in place of `oauth2.accessToken` in its own right for https://github.com/Budibase/budibase/issues/3827.

As for the `DrawerBindableInput`, that's a fair point. I hadn't considered it as an option when working on the UI elements. As you point out, that would absolutely remove the guess work for the user and certainly remove some of the parsing back-and-forth.

**Comment by aptkingston** [comment]
> @aptkingston Thanks for taking a look! Regarding the bindings, that's correct, they are enriched from a global user. Also yes, the `userBindings` are those currently exposed in the builder. My assumption was that this would mean parity between the builder and rest queries, but as you point out, for advanced functionality this could be rather limiting. To that end, should a specific set of bindings be created explicitly for the global user? Utilising the same syntax `{{ Current User.[query]}}` but a set of context specific bindings?
> 
> Some of the elements on the global user have nested elements like `oauth2.accessToken` or `thirdPartyProfile`. There is currently a suggestion to specifically add {{ OAuthToken }} in place of `oauth2.accessToken` in its own right for #3827.
> 
> As for the `DrawerBindableInput`, that's a fair point. I hadn't considered it as an option when working on the UI elements. As you point out, that would absolutely remove the guess work for the user and certainly remove some of the parsing back-and-forth.

Just following up on this - is it possible to enrich using the app user rather than the global user? I definitely feel that would enable a lot more use cases since they could actually use custom data relating to the user. Maybe it's not possible with the implementation but just wanted to check, and I wasn't sure if you were doing any more work on this or not.

**Review by shogunpurple — APPROVED** [review]
LGTM! This is a really solid piece of work 👌

**Pull request merged**
