### PR TITLE
Making it possible to create an internal table from the plus symbol

### PR DESCRIPTION
**Pull request by mike12345567**
## Description
Its been requested/suggested, quick UI update to allow creating internal tables from the datasource `+` menu, shown below:

## Screenshots
image
image

### CODE REVIEW

**Comment by aptkingston** [comment]
Thank you for this - my muscle memory of clicking the plus button to create tables never fully went away! 😆

**Comment by joebudi** [comment]
Wonderful. Should we add CSV as an option too? I'm not sure users will know it exists otherwise.

**Comment by mike12345567** [comment]
> Wonderful. Should we add CSV as an option too? I'm not sure users will know it exists otherwise.

Was thinking about this, might be better to just have the name for Budibase be `Internal/CSV` with out logo? Cause you'd still want to have the full table modal, so its really just making it obvious that the BB option is both.

**Review by shogunpurple — APPROVED** [review]
Nice one! Yeah have to agree, keep clicking plus as well 🤦

**Comment by mike12345567** [comment]
@joebudi how about this?

image

**Comment by joebudi** [comment]
> > Wonderful. Should we add CSV as an option too? I'm not sure users will know it exists otherwise.
> 
> Was thinking about this, might be better to just have the name for Budibase be `Internal/CSV` with our logo? Cause you'd still want to have the full table modal, so its really just making it obvious that the BB option is both.

We can still have the table modal for both.

**Comment by joebudi** [comment]
> @joebudi how about this?
> 
> image
> 

I think this works. Great job

**Pull request merged**
