### PR TITLE
Interactive builder preview and friendly containers

### PR DESCRIPTION
**Pull request by aptkingston**
## Description
The primary idea of this PR is to make containers simple to use to construct custom layouts, even for non technical users. This has been achieved by adding a bunch of enhancements to the builder preview to make it much more interactive.

### Component settings bar within the preview
image
When you have a container selected, a bar will appear above the container that allows you to quickly change component settings. New accessible settings have been added to containers to control the underlying flex properties, and these are what this bar controls. Each setting is split into groups, with each icon representing a single value. Each value has an icon and a tooltip when hovering, for a textual explanation of what each button does.

image

This settings bar has been implemented in a completely generic way and is totally controlled by the manifest file. This means we can add this bar to control any settings we want on any component by simply updating the manifest file now. The client library controls rendering this bar and postioning it so that it is always on screen, regardless of where your component is.

image

### Component selection improvements
image
When you have a component selected, the component's name will now be rendered as well as the exisiting blue border. This will also position itself inside the component if it would otherwise be off-screen.

image

How the selection state is rendered has been totally redone. Previously, the `styleable` helper took on additional responsibility of changing the styles of the target node to add border radius a a blue border. This was inconvenient for a number of reasons:
- You could not see any border styles you had applied when the component is selected as they were overridden
- The preview "jumps" whenever you select a component, because border is added which makes the DOM layout reflow and things move by a few pixels

This has been totally changed so that the client library is now responsible for rendering the selection state. The new selection state is rendered above everything else, and uses the target nodes client bounding box to know the dimenions and positions of where to render the seleciton border. The critical difference is that the selection state is now rendered totally outside the actual component - meaning you can see all of the component when it is selected, and there are no more jumps when selecting things.

### Component selection highlight on hover
https://user-images.githubusercontent.com/9075550/121677725-2cd1cf80-caae-11eb-8635-ec070d708d79.mp4

The component you're hovering over will now be displayed similarly to the selection state, just with a lighter colour. This makes the preview feel much more interactive and gives you a far better understandanding of the layout of your page, without having to keep selecting different components. This also displays the name of the component, does not cause page reflow and even works inside scrollable components or repeaters. (🙏 praise the `IntersectionObserver` browser API). Everything fades in and out nicely.

### Placeholders and empty states
image

To further improve the builder preview, all components that accept children will now automatically have empty state styles and placeholders applied by the client library. These mean that there will never be cases of 0 height blue lines any more, or not being able to select a component because it has dimenions of 0. Components that accept children also get a dashed border which really helps for things like containers, because you can easily see their bounding boxes and create layouts without having to apply hacky background colours etc.

I've also added and improved placeholders to other components that don't accept children but still benefit from placeholders, like `Heading`, `Paragraph` and all the charts.

All of these placeholder and empty state styles only apply when inside the builder preview of course, and will never be shown in a real app. Here's the same screen when previewing. The only thing visible is the repeater text when there aren't any rows, as that deliberately is user facing (it's a configurable setting).

image

### Responsive autoscreens
Autoscreens have been updated to use the new container flex props, as have the built in layouts. They have also all updated to be responsive and will shrink to small sizes on small screens as required. In general it will be easier to build responsive layouts due to some opinionated rules on containers now.

There's a fair it to this, so any feedback or change requests would be happily received. I'd recommend checking out this branch and playing around becauase it's the best way to get a feel for the new experience. You might want to create a new app so that all the containers have the flex props specified. Old apps will continue to function without any problems - but any existing CSS rules will override the new flex props so you will need to clear your styles to use the new settings bar.

### CODE REVIEW

**Review by kevmodrome — APPROVED** [review]
This is awesome @aptkingston 👏 👏 👏 👏 🥳 

Particularly like how you define it in the manifest.

LGTM!

**Comment by mike12345567** [comment]
That video is *chefkiss* 👌 

This looks downright incredible and an amazing improvement to the usability of the builder!

Incredible work 👏 👏 👏 👏 👏 👏 👏

**Comment by joebudi** [comment]
Wonderful work @aptkingston The new action bar alone provides the user with the right amount of flexibility, convenience, and power. Well done! Looking forward to using this.

**Review by shogunpurple — APPROVED** [review]
LGTM - this is incredible! Amazing work @aptkingston. The DOM API work that has been done to get this up and running is brilliant. 🚀

**Pull request merged**
