### PR TITLE
Fix prettier and other misc fixes

### LINKED ISSUE #1433: Cannot bind to calculated view of type "Count"
**Describe the bug**
Budibase crashes when we try to set a repeater's datasource to a calculated view, which is a "Count". Works ok with "Statistics "

**To Reproduce**
1. Create a view > calculate > count
2. Add a repeater
3. Set datasource to your view
4. Exception thrown - budibase freezes & data does not show

**Additional context**
```
dataBinding.js:240 Uncaught (in promise) TypeError: Cannot create property 'name' on string 'string'
    at dataBinding.js:240
    at Array.forEach (<anonymous>)
    at SC (dataBinding.js:238)
    at dataBinding.js:118
    at Array.forEach (<anonymous>)
    at EC (dataBinding.js:103)
    at vC (dataBinding.js:16)
    at Object.e.$$.update (PropertyControl.svelte:27)
    at Qe (index.mjs:1482)
    at new M6 (PropertyControl.svelte:72)
```

### PR DESCRIPTION
**Pull request by aptkingston**
## Description
This PR fixes prettier which was broken after it was recently updated. I've also ran a format over the whole codebase which should update everything to the latest built in recommendations. The 2 major changes I can see are:

1. Single param functions are now wrapped, e.g.
`a => {}` has become `(a) => {}`

2. Multiline component tags now have the closing tag on a new line, e.g.
```html
<Component
    prop={value}
    prop={value}
    prop={value}
    prop={value} />
```
has become
```html
<Component
    prop={value}
    prop={value}
    prop={value}
    prop={value}
/>
```
I didn't update prettier so I'm not proposing these changes - I'm just fixing it as currently `format` will throw errors and exit because of a couple of issues.

This also closes #1433 (certain views break datasources) and also fixes the BBUI `ModalContent` prop which was not standardised to use the single letter size props (`size="L"` for example).

Is anyone particularly offended by either of those latest prettier defaults? Personally I like having closing tags on a new line, but I'm not so fussed on forcing wrapping single param functions in parenthesis.

### CODE REVIEW

**Comment by kevmodrome** [comment]
Out of these: `a => {}` has become `(a) => {}` I much prefer the first one
The second one I don't have much of an opinion (as in I do not really care whichever way we end up going) on but I lean towards the first.

**Comment by shogunpurple** [comment]
I agree with this too. I like newline component closing tags but don't like the wrapping of single arg arrow functions. We should update the pretter config to allow that I think

**Comment by mike12345567** [comment]
Yeah I don't think there is any need to wrap single param functions, just adds more fluff when you're doing `maps`, `filters` etc.

**Comment by aptkingston** [comment]
Sounds good! I've updated the prettier config to be explicit so that any upstream default changes won't affect us (for these 2 rules at least).

**Pull request merged**
