### PR TITLE
Add camera choice option to QR scanner field

### PR DESCRIPTION
**Pull request by zedascouves**
## Description
_Allows selecting the camera for the QR scanner field. Issue https://github.com/Budibase/budibase/issues/11459._

Addresses: 
- `https://github.com/Budibase/budibase/issues/11459`

## Documentation
- [X] I have reviewed the budibase documentatation to verify if this feature requires any changes. If changes or new docs are required I have written them.

### CODE REVIEW

**Comment by zedascouves** [comment]
I have read the CLA Document and I hereby sign the CLA.

**Comment by zedascouves** [comment]
recheck

**Comment by zedascouves** [comment]
> @zedascouves can you please re-open this PR into `master` and we will merge it?

Hi! I'm sorry, I don't know how git works that well, so I'm not really sure what you mean... Do you mean that I should merge into Budibase:master, on a new pull request?

**Comment by shogunpurple** [comment]
@zedascouves yep, exactly that. We are planning on doing away with the `develop` branch altogether so we need to make the change to `master`

**Comment by zedascouves** [comment]
@shogunpurple I've corrected the spelling on the variable's names and opened a new pull request: https://github.com/Budibase/budibase/pull/12109.

I hope everything is up to spec...

Cheers!

**Pull request closed without merging**
