### PR TITLE
Update dd-trace to 4.20.0.

### PR DESCRIPTION
**Pull request by samwho**
This is a little bit of a Hail Mary because we're also seeing this bug: https://github.com/DataDog/dd-trace-js/issues/3866#issuecomment-1858912462. I'm skeptical this will work, but I think it's worth a try. Plus updating stuff is good practice.

I didn't go to the latest, 4.21.0, because of this: https://github.com/DataDog/dd-trace-js/issues/3887.

### CODE REVIEW

**Comment by adrinr** [comment]
Not sure why you did not go to `4.21.0`. How is that related to the other PR?

**Review by adrinr — APPROVED** [review]
LGTM, just a question about the version

**Comment by samwho** [comment]
Bleh. Monday morning. I was meant to link to a dd-trace-js bug and failed. Will fix it when my son stops climbing on me.

**Comment by samwho** [comment]
Fixed. Bug is this one: https://github.com/DataDog/dd-trace-js/issues/3887.

**Pull request merged**
