### PR TITLE
feat: made changes to worker and server packages to use global-agent …

### PR DESCRIPTION
**Pull request by StarZeus**
added ability to connect to internet-hosted resources (such as OIDC config and app templates) behind a proxy.

## Fixes
# 5422

### CODE REVIEW

**Comment by StarZeus** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by StarZeus** [comment]
recheck

**Review by shogunpurple — APPROVED** [review]
Hi @StarZeus - this change looks good to me and thank you for the contribution. I just would like to clarify if this solved it for your use case, and a bit about how `global-agent` works. Does it proxy **all** requests through the proxy specified as an env variable?

Also curious as to whether you have tested this inside your corporate environment and if it works as expected.

Thanks in advance!

**Comment by StarZeus** [comment]
Hi @shogunpurple - Yes, I have tested it in our environment and this has solved my issue now able to use it from our network. 
global-agent intercepts all call made via `http.request`. When there is any domain we want to exclude from proxying we can configure GLOBAL_AGENT_NO_PROXY and that's what I did for internal calls.

More Info : ```https://github.com/gajus/global-agent```

**Comment by shogunpurple** [comment]
@StarZeus this is good to go, you just need to fix the conflicts and then we are good to merge!

**Review by Rory-Powell — APPROVED** [review]
LGTM

**Comment by StarZeus** [comment]
@shogunpurple - resolved conflicts

**Comment by Rory-Powell** [comment]
@StarZeus I think you will need to merge the latest develop into this one to get the CI build to pass

**Comment by StarZeus** [comment]
@Rory-Powell - Merged latest changes from develop branch

**Pull request merged**
