### PR TITLE
Is in filter - only call startsWith if string type

### PR DESCRIPTION
**Pull request by melohagan**
## Description
Crash caused by trying to call `startsWith` on array.

Addresses: 
- https://github.com/Budibase/budibase/issues/7878

### CODE REVIEW

**Review by shogunpurple — APPROVED** [review]
LGTM!

**Review by aptkingston — APPROVED** [review]
I'm confused how this could break, because how can a value not be a string here? Perhaps with other operators it's possible to have a value that's an array, if we were letting them pick options from a multi select. If that's the case then I feel we should be resetting the expression value whenever the binding type changes (e.g. a binding type can only be a string), since there might be similar issues to this elsewhere. 

But in any case, this one is good to go in for now!

**Comment by aptkingston** [comment]
> @aptkingston I think it broke because of this commit: [350e023](https://github.com/Budibase/budibase/commit/350e0233e201e2441b8e4face337f13e3338640b)
> 
> Basically the **Is in** filter always expects the expression value to be an array.

Yep that would do it! We should really follow up that `if` statement with something like
```js
else if (operator !== Constants.OperatorOptions.In.value && Array.isArray(expression.value)) {
  expression.value = null
}
```
so that we clear the array again for any other operator. That would also fix this bug, but the current fix is totally fine to merge too. This additional check would just prevent other cases like this from happening.

**Comment by melohagan** [comment]
> > @aptkingston I think it broke because of this commit: [350e023](https://github.com/Budibase/budibase/commit/350e0233e201e2441b8e4face337f13e3338640b)
> > Basically the **Is in** filter always expects the expression value to be an array.
> 
> Yep that would do it! We should really follow up that `if` statement with something like
> 
> ```js
> else if (operator !== Constants.OperatorOptions.In.value && Array.isArray(expression.value)) {
>   expression.value = null
> }
> ```
> 
> so that we clear the array again for any other operator. That would also fix this bug, but the current fix is totally fine to merge too. This additional check would just prevent other cases like this from happening.

I made this change, but I also had to add in an **onChange** handler for the value type changing to get this to work without the original bug fix.
With that said, I left in the string type check for good measure.

**Comment by aptkingston** [comment]
The logic here is becoming a bit gnarly haha. I might jump on and see if it could be refactored a bit to reduce duplication and simplify things, just because this is now the sort of file that you could come back to in a few months and have no idea what's going on anymore!

**Comment by melohagan** [comment]
> The logic here is becoming a bit gnarly haha. I might jump on and see if it could be refactored a bit to reduce duplication and simplify things, just because this is now the sort of file that you could come back to in a few months and have no idea what's going on anymore!

That is true; thanks for taking a look! Handling array types within the filters has been a bit awkward.

**Comment by aptkingston** [comment]
@melohagan I've refactored the validation logic here which should make things much simpler to read and maintain over time! Do you want to have a look and see what you think? The only thing I didn't keep (deliberately) was the automatic conversion of comma-separated strings into real array values, as that can end up generating invalid selected options in the multi-select picker if the user just happens to have a comma inside a normal string.

**Comment by melohagan** [comment]
That looks great @aptkingston much cleaner, thank you!

NAB: The methods are called *validateX* e.g. `validateValue` but really it's cleaning or sanitising.

**Comment by aptkingston** [comment]
> That looks great @aptkingston much cleaner, thank you!
> 
> NAB: The methods are called _validateX_ e.g. `validateValue` but really it's cleaning or sanitising.

Sanitize sounds accurate to me! Have updated it.

**Pull request merged**
