### PR TITLE
Test in-memory search alongside all of our other search types, to ensure parity.

### PR DESCRIPTION
**Pull request by samwho**
## Description

This PR makes sure that our in-memory searching that we use in the frontend behaves the same as the backend searches by plugging them into the same test suite the backend ones use.

### CODE REVIEW

**Review by mike12345567 — APPROVED** [review]
LGTM - nice to get this actually tested!

**Comment by aptkingston** [comment]
Any idea if this PR would address https://github.com/Budibase/budibase/issues/13505#issuecomment-2060860157? I had noticed before we didn't properly support the "match any" function in the in-memory filtering.

**Comment by samwho** [comment]
@aptkingston Yes, I think it probably will. There was a bug in the way that the in-memory filter did matching where it wasn't correctly obeying the allOr param and I fixed that in this PR and I think what you describe in that comment would be fixed by what I did.

**Comment by aptkingston** [comment]
> @aptkingston Yes, I think it probably will. There was a bug in the way that the in-memory filter did matching where it wasn't correctly obeying the allOr param and I fixed that in this PR and I think what you describe in that comment would be fixed by what I did.

Super! Thanks.

**Pull request merged**
