### PR TITLE
Adds the NPS Feedback Form modal/popup

### PR DESCRIPTION
**Pull request by kevmodrome**
## Description
This PR adds  #1736 to the builder. It shows up after the user has clicked the Preview/Play button to preview their app. It uses a feedbackSubmitted cookie to check if the user has already submitted feedback. As discussed in the issue it might make sense to have that attached directly on the user so that they won't see it multiple times if using different devices.

## Screenshots
CleanShot 2021-07-21 at 12 34 03@2x

CleanShot 2021-07-21 at 13 09 12@2x

CleanShot 2021-07-21 at 13 09 19@2x

### CODE REVIEW

**Comment by joebudi** [comment]
@kevmodrome does the second modal have the same title at the first one?

**Comment by kevmodrome** [comment]
> @kevmodrome does the second modal have the same title at the first one?

Good catch! Fixed now.

**Comment by joebudi** [comment]
@kevmodrome nice one! One little design nitpick:
Could you align the page detail with the buttons - Page 2 of 3 should be center-aligned with the preview and next button.

And, on top of that, maybe replace the word Page with Step.

**Comment by kevmodrome** [comment]
> @kevmodrome nice one! One little design nitpick:
> Could you align the page detail with the buttons - Page 2 of 3 should be center-aligned with the preview and next button.
> 
> And, on top of that, maybe replace the word Page with Step.

Fixed and uploaded new images

**Review by aptkingston — APPROVED** [review]
LGTM! Just one question on the behaviour of it - since it uses cookies I think it's very likely that they'll see this pop up a few times. That's fine, but is there a way for them to easily dismiss it after they've already filled it in? I don't see a close icon or button, but does it go away with a click outside?

**Comment by kevmodrome** [comment]
> LGTM! Just one question on the behaviour of it - since it uses cookies I think it's very likely that they'll see this pop up a few times. That's fine, but is there a way for them to easily dismiss it after they've already filled it in? I don't see a close icon or button, but does it go away with a click outside?

Good q! There's currently no way to dismiss it, unsure what kind of UX @joebudi wants here?

**Comment by joebudi** [comment]
@aptkingston and @kevmodrome I don't think they (the users) should see it again, and again.

It will get annoying imo. There should be an X to close the modal and it should disappear if they click elsewhere.

We're asking for helpful information, but it should not upset the UX.

**Review by PClmnt — APPROVED** [review]
LGTM!

**Review by Rory-Powell — APPROVED** [review]
Looks good! 
NAB: Would be nice to store in the db like Joe said to prevent seeing it again, but that could come as a follow up

**Comment by kevmodrome** [comment]
@joebudi is this ok?

CleanShot 2021-07-22 at 12 09 27@2x

**Comment by joebudi** [comment]
> @joebudi is this ok?
> 
> CleanShot 2021-07-22 at 12 09 27@2x

Perfecto!

**Pull request merged**
