### PR TITLE
Changes relating to adding accountName to Account entity

### PR DESCRIPTION
**Pull request by melohagan**
## Description
Removing some unused code relating to this issue:
https://linear.app/budibase/issue/GRO-671/add-mandatory-field-name-to-account-entity-and-update-bpm-onboarding

**Tests should pass after this has been merged**: https://github.com/Budibase/account-portal/pull/759

### CODE REVIEW

**Review by 1998Shootinstar — APPROVED** [review]

**Review by 1998Shootinstar — CHANGES_REQUESTED** [review]
I need help

**Review by 1998Shootinstar — CHANGES_REQUESTED** [review]
Hi

**Comment by 1998Shootinstar** [comment]
GitHub com login,GitHub com name,Enterprise server user ids,GitHub com user,Enterprise server user,Visual studio subscription user,License type,GitHub com profile,GitHub com member roles,GitHub com enterprise roles,GitHub com verified domain emails,GitHub com saml name,GitHub com orgs with pending invites,GitHub com two factor auth,GitHub com two factor auth required by date,GitHub com cost center,Ghe license active,Ghe license start date,Ghe license end date,Enterprise server primary emails,Visual studio license status,Visual studio subscription email,Total user accounts
david,David Leal,"",true,false,false,,https://github.com/david,"",Pending administrator invitation,"",,"",false,,,,,,"",,,1
john,John McGrath,"",true,false,false,,https://github.com/john,"",Pending administrator invitation,"",,"",false,,,,,,"",,,1
o,Osman,"",true,false,false,,https://github.com/o,"",Pending administrator invitation,"",,"",false,,,,,,"",,,1
shalby,,"",true,false,false,,https://github.com/shalby,"",Pending administrator invitation,"",,"",false,,,,,,"",,,1
1998Shootinstar,,"",true,false,false,Enterprise,https://github.com/1998Shootinstar,Shootin1:Owner,"Owner, Member","",,"",false,,,,,,"",,,1

**Review by samwho — COMMENTED** [review]
Looks like you may need to update the account-portal submodule to get the tests to pass.

**Review by jvcalderon — APPROVED** [review]
LGTM

**Pull request merged**
