### PR TITLE
Use clickoutside library to stop mouseup closing side panel

### PR DESCRIPTION
**Pull request by melohagan**
## Description
A slightly annoying bug was happening were clicking down within the side panel, and releasing outside the side panel would close it. This could happen when using the mouse to select the contents of a field for example.

This bug is easily fixed by requiring that only **mousedown** outside of the side panel will close it.

## Addresses
- https://github.com/Budibase/budibase/issues/10762

## Screenshots
fields_bug

### CODE REVIEW

**Comment by melohagan** [comment]
@aptkingston Well that was easier than I thought! 😄 

Changing the event handler to `mousedown` seems to do the trick. You were right about date pickers not being handled correctly, but that is fixed with this change.
Any other thoughts or areas to test?

**Comment by aptkingston** [comment]
Nearly impossible to know the full extent of any side effects here because clickOutside is used by a large amount of components, but we'll discover any issues over time of there are any. In principle I can't think of any glaring reason that we can't just use mouse down here. The sanity check is just that common things work - modals, popovers, datepickers, grid cell popovers etc all close properly still.

**Comment by melohagan** [comment]
> Nearly impossible to know the full extent of any side effects here because clickOutside is used by a large amount of components, but we'll discover any issues over time of there are any. In principle I can't think of any glaring reason that we can't just use mouse down here. The sanity check is just that common things work - modals, popovers, datepickers, grid cell popovers etc all close properly still.

Hmm, for the Grid view it does alter the behaviour in a slightly bad way:
https://github.com/Budibase/budibase/assets/101575380/c0193023-1283-4565-9dc2-a87d7cc3770a

I would much prefer to be able to pass in the event handler on a per usage basis (like that library). I'll see if I can figure that out.

**Comment by aptkingston** [comment]
> > Nearly impossible to know the full extent of any side effects here because clickOutside is used by a large amount of components, but we'll discover any issues over time of there are any. In principle I can't think of any glaring reason that we can't just use mouse down here. The sanity check is just that common things work - modals, popovers, datepickers, grid cell popovers etc all close properly still.
> 
> Hmm, for the Grid view it does alter the behaviour in a slightly bad way: https://github.com/Budibase/budibase/assets/101575380/c0193023-1283-4565-9dc2-a87d7cc3770a
> 
> I would much prefer to be able to pass in the event handler on a per usage basis (like that library). I'll see if I can figure that out.

I'm not sure we can do it on a per usage basis - we deliberately use a single listener, as if we constructed one every time we would end up with potentially 100s of global click event listeners. You could potentially use a single click and a single mousedown, and support passing in a type, which would then use the appropriate listener.

**Comment by melohagan** [comment]
I think this is a safer approach now if you want to take a look @aptkingston

**Review by aptkingston — APPROVED** [review]
Yea this is definitely safer. It does have the side effect of making the `contextmenu` listener completely redundant since nothing is ever configured with an allowedType of `contextmenu`, so you can probably just remove that listener. I don't think it's particularly important to close things on a context menu click.

**Pull request merged**
