### PR TITLE
Routing ui

### PR DESCRIPTION
**Pull request by shogunpurple**
## Description
Addresses https://github.com/Budibase/budibase/issues/842

This PR contains code to display pages under their respective routes from the new backend routing API. This work is the underlying foundation for the access level UI that will allow users to attach roles to particular screens.

- Refactored drag and drop into its own separate store with actions
- Moved existing component hierarchy code into a folder with the new tree structure components

## Screenshots
Screenshot 2020-11-19 at 15 31 11

### CODE REVIEW

**Review by mike12345567 — APPROVED** [review]
LGTM! Some good code quality improvements too throughout!

**Review by aptkingston — APPROVED** [review]
Looks great!

NAB - few thoughts which maybe @joebudi could input on:
- Should we use a folder icon for the top level routes?
- Should we display the home screen as just "Home" rather than "/"?

**Comment by joebudi** [comment]
> Looks great!
> 
> NAB - few thoughts which maybe @joebudi could input on:
> 
> * Should we use a folder icon for the top level routes? Yes!
> * Should we display the home screen as just "Home" rather than "/"? Yes!

I am not sure if there is another way, but it seems extra effort to have to open the home top-level route, then open the home screen. Thoughts @shogunpurple and @aptkingston

**Comment by shogunpurple** [comment]
@joebudi @aptkingston great suggestions. Will update those.

`I am not sure if there is another way, but it seems extra effort to have to open the home top-level route, then open the home screen.`.

If we change the inner screen to "Home", then it makes more sense - since you are seeing the `/` route above it, you know it's the route, and "Home" is the screen you will be taken to. Bear in mind there could be a few screens here for different access levels as well

**Comment by shogunpurple** [comment]
Updated:

Screenshot 2020-11-19 at 20 49 39

**Pull request merged**
