### PR TITLE
Add snippets to app imports

### PR DESCRIPTION
**Pull request by aptkingston**
## Description
Add snippets to app imports.

## Addresses
- https://github.com/Budibase/budibase/issues/13416
- https://linear.app/budibase/issue/BUDI-8149/snippets-dont-get-transfered-whenever-exporting-and-importing-an-app

### CODE REVIEW

**Comment by samwho** [comment]
@aptkingston would you mind adding a test for this fix? 🙏 Happy to help if needed.

**Review by deanhannigan — APPROVED** [review]
LGTM!

**Review by adrinr — APPROVED** [review]

**Comment by aptkingston** [comment]
> @aptkingston would you mind adding a test for this fix? 🙏 Happy to help if needed.

There doesn't appear to be any tests for checking metadata is copied over at the moment, so I'll have to come up with a new suite of tests to ensure all the other keys are copied over too as I'm only adding another key to copy over with this change. I'll maybe store a new app export and use that as reference because I don't think there's a better way to test this.

**Comment by samwho** [comment]
Would it not be possible to create an app, populate its metadata, do an export, and then do an import, then assert agains the newly imported app that things have been populated correctly?

**Comment by aptkingston** [comment]
That would work too but I figured it would require filesystem access to store the temp export, but maybe I can keep it all in memory. Maybe filesystem access is OK too, but just seems a little flaky to me. I'll see if I can do it all in memory.

**Comment by samwho** [comment]
I'm _fairly sure_ we access the filesystem in some other tests and it doesn't cause flakes. I wouldn't worry about it. Filesystem access certainly _shouldn't_ be flaky, if it is that's something we'd want to investigate.

**Pull request merged**
